"use client";

import { useEffect, useRef, useState, type MouseEvent } from "react";
import Image from "next/image";
import { ChevronDown } from "lucide-react";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import Container from "@/components/common/Container";
import Button from "@/components/common/Button";
import SectionRadialGlow from "@/components/common/SectionRadialGlow";
import { useSectionHeaderReveal } from "@/hooks/useSectionHeaderReveal";

gsap.registerPlugin(ScrollTrigger);

const POLICY_TYPES = [
  "Builder's Risk",
  "Business Owner's Policy",
  "Commercial Auto",
  "Commercial General Liability",
  "Commercial Property",
  "Cyber",
  "Miscellaneous Professional Liability",
  "Worker's Compensation",
] as const;

const INDUSTRIES = [
  "327910 - ABRASIVE PRODUCT MANUFACTURING",
  "325520 - ADHESIVE MANUFACTURING",
  "924110 - ADMINISTRATION OF AIR AND WATER RESOURCE AND SOLID WASTE MANAGEMENT PROGRAMS",
  "924120 - ADMINISTRATION OF CONSERVATION PROGRAMS",
  "923110 - ADMINISTRATION OF EDUCATION PROGRAMS",
  "926110 - ADMINISTRATION OF GENERAL ECONOMIC PROGRAMS",
  "925110 - ADMINISTRATION OF HOUSING PROGRAMS",
  "923130 - ADMINISTRATION OF HUMAN RESOURCE PROGRAMS (EXCEPT EDUCATION, PUBLIC HEALTH, AND VETERANS' AFFAIRS PROGRAMS)",
  "923120 - ADMINISTRATION OF PUBLIC HEALTH PROGRAMS",
  "925120 - ADMINISTRATION OF URBAN PLANNING AND COMMUNITY AND RURAL DEVELOPMENT",
  "923140 - ADMINISTRATION OF VETERANS' AFFAIRS",
  "541611 - ADMINISTRATIVE MANAGEMENT AND GENERAL MANAGEMENT CONSULTING SERVICES",
  "541810 - ADVERTISING AGENCIES",
  "541870 - ADVERTISING MATERIAL DISTRIBUTION SERVICES",
  "711410 - AGENTS AND MANAGERS FOR ARTISTS, ATHLETES, ENTERTAINERS, AND OTHER PUBLIC FIGURES",
  "517122 - AGENTS FOR WIRELESS TELECOMMUNICATIONS SERVICES",
  "333912 - AIR AND GAS COMPRESSOR MANUFACTURING",
  "488111 - AIR TRAFFIC CONTROL",
  "333415 - AIR-CONDITIONING AND WARM AIR HEATING EQUIPMENT AND COMMERCIAL AND INDUSTRIAL REFRIGERATION EQUIPMENT MANUFACTURING",
  "336412 - AIRCRAFT ENGINE AND ENGINE PARTS MANUFACTURING",
  "336411 - AIRCRAFT MANUFACTURING",
  "713990 - ALL OTHER AMUSEMENT AND RECREATION INDUSTRIES",
  "112990 - ALL OTHER ANIMAL PRODUCTION",
  "811198 - ALL OTHER AUTOMOTIVE REPAIR AND MAINTENANCE",
  "325199 - ALL OTHER BASIC ORGANIC CHEMICAL MANUFACTURING",
  "561499 - ALL OTHER BUSINESS SUPPORT SERVICES",
  "532289 - ALL OTHER CONSUMER GOODS RENTAL",
  "322299 - ALL OTHER CONVERTED PAPER PRODUCT MANUFACTURING",
  "455219 - ALL OTHER GENERAL MERCHANDISE RETAILERS",
  "111199 - ALL OTHER GRAIN FARMING",
  "456199 - ALL OTHER HEALTH AND PERSONAL CARE RETAILERS",
  "449129 - ALL OTHER HOME FURNISHINGS RETAILERS",
  "333248 - ALL OTHER INDUSTRIAL MACHINERY MANUFACTURING",
  "524298 - ALL OTHER INSURANCE RELATED ACTIVITIES",
  "541199 - ALL OTHER LEGAL SERVICES",
  "621999 - ALL OTHER MISCELLANEOUS AMBULATORY HEALTH CARE SERVICES",
  "325998 - ALL OTHER MISCELLANEOUS CHEMICAL PRODUCT AND PREPARATION MANUFACTURING",
  "111998 - ALL OTHER MISCELLANEOUS CROP FARMING",
  "335999 - ALL OTHER MISCELLANEOUS ELECTRICAL EQUIPMENT AND COMPONENT MANUFACTURING",
  "332999 - ALL OTHER MISCELLANEOUS FABRICATED METAL PRODUCT MANUFACTURING",
  "311999 - ALL OTHER MISCELLANEOUS FOOD MANUFACTURING",
  "333998 - ALL OTHER MISCELLANEOUS GENERAL PURPOSE MACHINERY MANUFACTURING",
  "339999 - ALL OTHER MISCELLANEOUS MANUFACTURING",
  "327999 - ALL OTHER MISCELLANEOUS NONMETALLIC MINERAL PRODUCT MANUFACTURING",
  "459999 - ALL OTHER MISCELLANEOUS RETAILERS",
  "611699 - ALL OTHER MISCELLANEOUS SCHOOLS AND INSTRUCTION",
  "314999 - ALL OTHER MISCELLANEOUS TEXTILE PRODUCT MILLS",
  "562998 - ALL OTHER MISCELLANEOUS WASTE MANAGEMENT SERVICES",
  "321999 - ALL OTHER MISCELLANEOUS WOOD PRODUCT MANUFACTURING",
  "621498 - ALL OTHER OUTPATIENT CARE CENTERS",
  "812990 - ALL OTHER PERSONAL SERVICES",
  "324199 - ALL OTHER PETROLEUM AND COAL PRODUCTS MANUFACTURING",
  "486990 - ALL OTHER PIPELINE TRANSPORTATION",
  "326199 - ALL OTHER PLASTICS PRODUCT MANUFACTURING",
  "541990 - ALL OTHER PROFESSIONAL, SCIENTIFIC, AND TECHNICAL SERVICES",
  "513199 - ALL OTHER PUBLISHERS",
  "326299 - ALL OTHER RUBBER PRODUCT MANUFACTURING",
  "445298 - ALL OTHER SPECIALTY FOOD RETAILERS",
  "238990 - ALL OTHER SPECIALTY TRADE CONTRACTORS",
  "488999 - ALL OTHER SUPPORT ACTIVITIES FOR TRANSPORTATION",
  "561990 - ALL OTHER SUPPORT SERVICES",
  "517810 - ALL OTHER TELECOMMUNICATIONS",
  "485999 - ALL OTHER TRANSIT AND GROUND PASSENGER TRANSPORTATION",
  "336999 - ALL OTHER TRANSPORTATION EQUIPMENT MANUFACTURING",
  "561599 - ALL OTHER TRAVEL ARRANGEMENT AND RESERVATION SERVICES",
  "721199 - ALL OTHER TRAVELER ACCOMMODATION",
  "331313 - ALUMINA REFINING AND PRIMARY ALUMINUM PRODUCTION",
  "331524 - ALUMINUM FOUNDRIES (EXCEPT DIE-CASTING)",
  "331315 - ALUMINUM SHEET, PLATE, AND FOIL MANUFACTURING",
  "621910 - AMBULANCE SERVICES",
  "921150 - AMERICAN INDIAN AND ALASKA NATIVE TRIBAL GOVERNMENTS",
  "332993 - AMMUNITION (EXCEPT SMALL ARMS) MANUFACTURING",
  "713110 - AMUSEMENT AND THEME PARKS",
  "713120 - AMUSEMENT ARCADES",
  "334516 - ANALYTICAL LABORATORY INSTRUMENT MANUFACTURING",
  "311611 - ANIMAL (EXCEPT POULTRY) SLAUGHTERING",
  "112910 - APICULTURE",
  "315990 - APPAREL ACCESSORIES AND OTHER APPAREL MANUFACTURING",
  "315120 - APPAREL KNITTING MILLS",
  "111331 - APPLE ORCHARDS",
  "811412 - APPLIANCE REPAIR AND MAINTENANCE",
  "611513 - APPRENTICESHIP TRAINING",
  "541310 - ARCHITECTURAL SERVICES",
  "561613 - ARMORED CAR SERVICES",
  "459920 - ART DEALERS",
  "325220 - ARTIFICIAL AND SYNTHETIC FIBERS AND FILAMENTS MANUFACTURING",
  "324121 - ASPHALT PAVING MIXTURE AND BLOCK MANUFACTURING",
  "324122 - ASPHALT SHINGLE AND COATING MATERIALS MANUFACTURING",
  "623312 - ASSISTED LIVING FACILITIES FOR THE ELDERLY",
  "334310 - AUDIO AND VIDEO EQUIPMENT MANUFACTURING",
  "334512 - AUTOMATIC ENVIRONMENTAL CONTROL MANUFACTURING FOR RESIDENTIAL, COMMERCIAL, AND APPLIANCE USE",
  "336110 - AUTOMOBILE AND LIGHT DUTY MOTOR VEHICLE MANUFACTURING",
  "423110 - AUTOMOBILE AND OTHER MOTOR VEHICLE MERCHANT WHOLESALERS",
  "611692 - AUTOMOBILE DRIVING SCHOOLS",
  "811121 - AUTOMOTIVE BODY, PAINT, AND INTERIOR REPAIR AND MAINTENANCE",
  "811122 - AUTOMOTIVE GLASS REPLACEMENT SHOPS",
  "811191 - AUTOMOTIVE OIL CHANGE AND LUBRICATION SHOPS",
  "441330 - AUTOMOTIVE PARTS AND ACCESSORIES RETAILERS",
  "445291 - BAKED GOODS RETAILERS",
  "332991 - BALL AND ROLLER BEARING MANUFACTURING",
  "812111 - BARBER SHOPS",
  "334412 - BARE PRINTED CIRCUIT BOARD MANUFACTURING",
  "335910 - BATTERY MANUFACTURING",
  "812112 - BEAUTY SALONS",
  "721191 - BED-AND-BREAKFAST INNS",
  "112111 - BEEF CATTLE RANCHING AND FARMING",
  "424810 - BEER AND ALE MERCHANT WHOLESALERS",
  "445320 - BEER, WINE, AND LIQUOR RETAILERS",
  "311313 - BEET SUGAR MANUFACTURING",
  "111334 - BERRY (EXCEPT STRAWBERRY) FARMING",
  "325414 - BIOLOGICAL PRODUCT (EXCEPT DIAGNOSTIC) MANUFACTURING",
  "221117 - BIOMASS ELECTRIC POWER GENERATION",
  "337920 - BLIND AND SHADE MANUFACTURING",
  "621991 - BLOOD AND ORGAN BANKS",
  "336612 - BOAT BUILDING",
  "441222 - BOAT DEALERS",
  "332722 - BOLT, NUT, SCREW, RIVET, AND WASHER MANUFACTURING",
  "513130 - BOOK PUBLISHERS",
  "459210 - BOOK RETAILERS AND NEWS DEALERS",
  "424920 - BOOK, PERIODICAL, AND NEWSPAPER MERCHANT WHOLESALERS",
  "323117 - BOOKS PRINTING",
  "312112 - BOTTLED WATER MANUFACTURING",
  "713950 - BOWLING CENTERS",
  "311230 - BREAKFAST CEREAL MANUFACTURING",
  "312120 - BREWERIES",
  "423320 - BRICK, STONE, AND RELATED CONSTRUCTION MATERIAL MERCHANT WHOLESALERS",
  "313210 - BROAD WOVEN FABRIC MILLS",
  "112320 - BROILERS AND OTHER MEAT TYPE CHICKEN PRODUCTION",
  "339994 - BROOM, BRUSH, AND MOP MANUFACTURING",
  "541350 - BUILDING INSPECTION SERVICES",
  "339995 - BURIAL CASKET MANUFACTURING",
  "485113 - BUS AND OTHER MOTOR VEHICLE TRANSIT SYSTEMS",
  "611410 - BUSINESS AND SECRETARIAL SCHOOLS",
  "813910 - BUSINESS ASSOCIATIONS",
  "722514 - CAFETERIAS, GRILL BUFFETS, AND BUFFETS",
  "311314 - CANE SUGAR MANUFACTURING",
  "334416 - CAPACITOR, RESISTOR, COIL, TRANSFORMER, AND OTHER INDUCTOR MANUFACTURING",
  "811192 - CAR WASHES",
  "335991 - CARBON AND GRAPHITE PRODUCT MANUFACTURING",
  "314110 - CARPET AND RUG MILLS",
  "561740 - CARPET AND UPHOLSTERY CLEANING SERVICES",
  "721120 - CASINO HOTELS",
  "713210 - CASINOS (EXCEPT CASINO HOTELS)",
  "722320 - CATERERS",
  "112112 - CATTLE FEEDLOTS",
  "327310 - CEMENT MANUFACTURING",
  "812220 - CEMETERIES AND CREMATORIES",
  "485510 - CHARTER BUS INDUSTRY",
  "311513 - CHEESE MANUFACTURING",
  "112310 - CHICKEN EGG PRODUCTION",
  "624110 - CHILD AND YOUTH SERVICES",
  "624410 - CHILD CARE SERVICES",
  "311351 - CHOCOLATE AND CONFECTIONERY MANUFACTURING FROM CACAO BEANS",
  "111320 - CITRUS (EXCEPT ORANGE) GROVES",
  "813410 - CIVIC AND SOCIAL ORGANIZATIONS",
  "524291 - CLAIMS ADJUSTING",
  "327120 - CLAY BUILDING MATERIAL AND REFRACTORIES MANUFACTURING",
  "424350 - CLOTHING AND CLOTHING ACCESSORIES MERCHANT WHOLESALERS",
  "458110 - CLOTHING AND CLOTHING ACCESSORIES RETAILERS",
  "423520 - COAL AND OTHER MINERAL AND ORE MERCHANT WHOLESALERS",
  "483113 - COASTAL AND GREAT LAKES FREIGHT TRANSPORTATION",
  "483114 - COASTAL AND GREAT LAKES PASSENGER TRANSPORTATION",
  "311920 - COFFEE AND TEA MANUFACTURING",
  "812310 - COIN-OPERATED LAUNDRIES AND DRYCLEANERS",
  "561440 - COLLECTION AGENCIES",
  "611310 - COLLEGES, UNIVERSITIES, AND PROFESSIONAL SCHOOLS",
  "532411 - COMMERCIAL AIR, RAIL, AND WATER TRANSPORTATION EQUIPMENT RENTAL AND LEASING",
  "811310 - COMMERCIAL AND INDUSTRIAL MACHINERY AND EQUIPMENT (EXCEPT AUTOMOTIVE AND ELECTRONIC) REPAIR AND MAINTENANCE",
  "236220 - COMMERCIAL AND INSTITUTIONAL BUILDING CONSTRUCTION",
  "333310 - COMMERCIAL AND SERVICE INDUSTRY MACHINERY MANUFACTURING",
  "311812 - COMMERCIAL BAKERIES",
  "522110 - COMMERCIAL BANKING",
  "541922 - COMMERCIAL PHOTOGRAPHY",
  "323111 - COMMERCIAL PRINTING (EXCEPT SCREEN AND BOOKS)",
  "323113 - COMMERCIAL SCREEN PRINTING",
  "335132 - COMMERCIAL, INDUSTRIAL, AND INSTITUTIONAL ELECTRIC LIGHTING FIXTURE MANUFACTURING",
  "523160 - COMMODITY CONTRACTS INTERMEDIATION",
  "624210 - COMMUNITY FOOD SERVICES",
  "485112 - COMMUTER RAIL SYSTEMS",
  "325315 - COMPOST MANUFACTURING",
  "423430 - COMPUTER AND COMPUTER PERIPHERAL EQUIPMENT AND SOFTWARE MERCHANT WHOLESALERS",
  "541513 - COMPUTER FACILITIES MANAGEMENT SERVICES",
  "334112 - COMPUTER STORAGE DEVICE MANUFACTURING",
  "541512 - COMPUTER SYSTEMS DESIGN SERVICES",
  "334118 - COMPUTER TERMINAL AND OTHER COMPUTER PERIPHERAL EQUIPMENT MANUFACTURING",
  "611420 - COMPUTER TRAINING",
  "518210 - COMPUTING INFRASTRUCTURE PROVIDERS, DATA PROCESSING, WEB HOSTING, AND RELATED SERVICES",
  "327331 - CONCRETE BLOCK AND BRICK MANUFACTURING",
  "327332 - CONCRETE PIPE MANUFACTURING",
  "445292 - CONFECTIONERY AND NUT RETAILERS",
  "311352 - CONFECTIONERY MANUFACTURING FROM PURCHASED CHOCOLATE",
  "424450 - CONFECTIONERY MERCHANT WHOLESALERS",
  "423810 - CONSTRUCTION AND MINING (EXCEPT OIL WELL) MACHINERY AND EQUIPMENT MERCHANT WHOLESALERS",
  "333120 - CONSTRUCTION MACHINERY MANUFACTURING",
  "212321 - CONSTRUCTION SAND AND GRAVEL MINING",
  "532412 - CONSTRUCTION, MINING, AND FORESTRY MACHINERY AND EQUIPMENT RENTAL AND LEASING",
  "532210 - CONSUMER ELECTRONICS AND APPLIANCES RENTAL",
  "522291 - CONSUMER LENDING",
  "623311 - CONTINUING CARE RETIREMENT COMMUNITIES",
  "445131 - CONVENIENCE RETAILERS",
  "561920 - CONVENTION AND TRADE SHOW ORGANIZERS",
  "561591 - CONVENTION AND VISITORS BUREAUS",
  "333922 - CONVEYOR AND CONVEYING EQUIPMENT MANUFACTURING",
  "311821 - COOKIE AND CRACKER MANUFACTURING",
  "331420 - COPPER ROLLING, DRAWING, EXTRUDING, AND ALLOYING",
  "212230 - COPPER, NICKEL, LEAD, AND ZINC MINING",
  "111150 - CORN FARMING",
  "551114 - CORPORATE, SUBSIDIARY, AND REGIONAL MANAGING OFFICES",
  "922140 - CORRECTIONAL INSTITUTIONS",
  "322211 - CORRUGATED AND SOLID FIBER BOX MANUFACTURING",
  "456120 - COSMETICS, BEAUTY SUPPLIES, AND PERFUME RETAILERS",
  "611511 - COSMETOLOGY AND BARBER SCHOOLS",
  "111920 - COTTON FARMING",
  "115111 - COTTON GINNING",
  "492110 - COURIERS AND EXPRESS DELIVERY SERVICES",
  "561492 - COURT REPORTING AND STENOTYPE SERVICES",
  "922110 - COURTS",
  "311512 - CREAMERY BUTTER MANUFACTURING",
  "561450 - CREDIT BUREAUS",
  "522210 - CREDIT CARD ISSUING",
  "522130 - CREDIT UNIONS",
  "115113 - CROP HARVESTING, PRIMARILY BY MACHINE",
  "211120 - CRUDE PETROLEUM EXTRACTION",
  "212313 - CRUSHED AND BROKEN GRANITE MINING AND QUARRYING",
  "212312 - CRUSHED AND BROKEN LIMESTONE MINING AND QUARRYING",
  "335931 - CURRENT-CARRYING WIRING DEVICE MANUFACTURING",
  "314120 - CURTAIN AND LINEN MILLS",
  "337212 - CUSTOM ARCHITECTURAL WOODWORK AND MILLWORK MANUFACTURING",
  "325991 - CUSTOM COMPOUNDING OF PURCHASED RESINS",
  "541511 - CUSTOM COMPUTER PROGRAMMING SERVICES",
  "332114 - CUSTOM ROLL FORMING",
  "315210 - CUT AND SEW APPAREL CONTRACTORS",
  "315250 - CUT AND SEW APPAREL MANUFACTURING (EXCEPT CONTRACTORS)",
  "321912 - CUT STOCK, RESAWING LUMBER, AND PLANING",
  "327991 - CUT STONE AND STONE PRODUCT MANUFACTURING",
  "333515 - CUTTING TOOL AND MACHINE TOOL ACCESSORY MANUFACTURING",
  "325194 - CYCLIC CRUDE, INTERMEDIATE, AND GUM AND WOOD CHEMICAL MANUFACTURING",
  "112120 - DAIRY CATTLE AND MILK PRODUCTION",
  "424430 - DAIRY PRODUCT (EXCEPT DRIED OR CANNED) MERCHANT WHOLESALERS",
  "711120 - DANCE COMPANIES",
  "483111 - DEEP SEA FREIGHT TRANSPORTATION",
  "483112 - DEEP SEA PASSENGER TRANSPORTATION",
  "339114 - DENTAL EQUIPMENT AND SUPPLIES MANUFACTURING",
  "339116 - DENTAL LABORATORIES",
  "455110 - DEPARTMENT STORES",
  "621512 - DIAGNOSTIC IMAGING CENTERS",
  "812191 - DIET AND WEIGHT REDUCING CENTERS",
  "212311 - DIMENSION STONE MINING AND QUARRYING",
  "524114 - DIRECT HEALTH AND MEDICAL INSURANCE CARRIERS",
  "524113 - DIRECT LIFE INSURANCE CARRIERS",
  "541860 - DIRECT MAIL ADVERTISING",
  "524126 - DIRECT PROPERTY AND CASUALTY INSURANCE CARRIERS",
  "524127 - DIRECT TITLE INSURANCE CARRIERS",
  "513140 - DIRECTORY AND MAILING LIST PUBLISHERS",
  "312140 - DISTILLERIES",
  "561410 - DOCUMENT PREPARATION SERVICES",
  "311111 - DOG AND CAT FOOD MANUFACTURING",
  "339930 - DOLL, TOY, AND GAME MANUFACTURING",
  "541340 - DRAFTING SERVICES",
  "311423 - DRIED AND DEHYDRATED FOOD MANUFACTURING",
  "213111 - DRILLING OIL AND GAS WELLS",
  "722410 - DRINKING PLACES (ALCOHOLIC BEVERAGES)",
  "512132 - DRIVE-IN MOTION PICTURE THEATERS",
  "424210 - DRUGS AND DRUGGISTS' SUNDRIES MERCHANT WHOLESALERS",
  "311824 - DRY PASTA, DOUGH, AND FLOUR MIXES MANUFACTURING FROM PURCHASED FLOUR",
  "111130 - DRY PEA AND BEAN FARMING",
  "311514 - DRY, CONDENSED, AND EVAPORATED DAIRY PRODUCT MANUFACTURING",
  "812320 - DRYCLEANING AND LAUNDRY SERVICES (EXCEPT COIN-OPERATED)",
  "238310 - DRYWALL AND INSULATION CONTRACTORS",
  "112130 - DUAL-PURPOSE CATTLE RANCHING AND FARMING",
  "611710 - EDUCATIONAL SUPPORT SERVICES",
  "221121 - ELECTRIC BULK POWER TRANSMISSION AND CONTROL",
  "335139 - ELECTRIC LAMP BULB AND OTHER LIGHTING EQUIPMENT MANUFACTURING",
  "221122 - ELECTRIC POWER DISTRIBUTION",
  "423610 - ELECTRICAL APPARATUS AND EQUIPMENT, WIRING SUPPLIES, AND RELATED EQUIPMENT MERCHANT WHOLESALERS",
  "238210 - ELECTRICAL CONTRACTORS AND OTHER WIRING INSTALLATION CONTRACTORS",
  "334510 - ELECTROMEDICAL AND ELECTROTHERAPEUTIC APPARATUS MANUFACTURING",
  "811210 - ELECTRONIC AND PRECISION EQUIPMENT REPAIR AND MAINTENANCE",
  "334111 - ELECTRONIC COMPUTER MANUFACTURING",
  "334417 - ELECTRONIC CONNECTOR MANUFACTURING",
  "449210 - ELECTRONICS AND APPLIANCE RETAILERS",
  "332813 - ELECTROPLATING, PLATING, POLISHING, ANODIZING, AND COLORING",
  "611110 - ELEMENTARY AND SECONDARY SCHOOLS",
  "333921 - ELEVATOR AND MOVING STAIRWAY MANUFACTURING",
  "624230 - EMERGENCY AND OTHER RELIEF SERVICES",
  "561311 - EMPLOYMENT PLACEMENT AGENCIES",
  "321215 - ENGINEERED WOOD MEMBER MANUFACTURING",
  "541330 - ENGINEERING SERVICES",
  "813312 - ENVIRONMENT, CONSERVATION AND WILDLIFE ORGANIZATIONS",
  "541620 - ENVIRONMENTAL CONSULTING SERVICES",
  "325193 - ETHYL ALCOHOL MANUFACTURING",
  "611691 - EXAM PREPARATION AND TUTORING",
  "921140 - EXECUTIVE AND LEGISLATIVE OFFICES, COMBINED",
  "921110 - EXECUTIVE OFFICES",
  "561312 - EXECUTIVE SEARCH SERVICES",
  "325920 - EXPLOSIVES MANUFACTURING",
  "561710 - EXTERMINATING AND PEST CONTROL SERVICES",
  "313320 - FABRIC COATING MILLS",
  "332996 - FABRICATED PIPE AND PIPE FITTING MANUFACTURING",
  "332312 - FABRICATED STRUCTURAL METAL MANUFACTURING",
  "561210 - FACILITIES SUPPORT SERVICES",
  "621410 - FAMILY PLANNING CENTERS",
  "423820 - FARM AND GARDEN MACHINERY AND EQUIPMENT MERCHANT WHOLESALERS",
  "115115 - FARM LABOR CONTRACTORS AND CREW LEADERS",
  "333111 - FARM MACHINERY AND EQUIPMENT MANUFACTURING",
  "115116 - FARM MANAGEMENT SERVICES",
  "493130 - FARM PRODUCT WAREHOUSING AND STORAGE",
  "424910 - FARM SUPPLIES MERCHANT WHOLESALERS",
  "339993 - FASTENER, BUTTON, NEEDLE, AND PIN MANUFACTURING",
  "311225 - FATS AND OILS REFINING AND BLENDING",
  "325314 - FERTILIZER (MIXING ONLY) MANUFACTURING",
  "335921 - FIBER OPTIC CABLE MANUFACTURING",
  "313110 - FIBER, YARN, AND THREAD MILLS",
  "522320 - FINANCIAL TRANSACTIONS PROCESSING, RESERVE, AND CLEARINGHOUSE ACTIVITIES",
  "611610 - FINE ARTS SCHOOLS",
  "112511 - FINFISH FARMING AND FISH HATCHERIES",
  "114111 - FINFISH FISHING",
  "238350 - FINISH CARPENTRY CONTRACTORS",
  "922160 - FIRE PROTECTION",
  "424460 - FISH AND SEAFOOD MERCHANT WHOLESALERS",
  "445250 - FISH AND SEAFOOD RETAILERS",
  "713940 - FITNESS AND RECREATIONAL SPORTS CENTERS",
  "327211 - FLAT GLASS MANUFACTURING",
  "311930 - FLAVORING SYRUP AND CONCENTRATE MANUFACTURING",
  "611512 - FLIGHT TRAINING",
  "449121 - FLOOR COVERING RETAILERS",
  "238330 - FLOORING CONTRACTORS",
  "111422 - FLORICULTURE PRODUCTION",
  "459310 - FLORISTS",
  "311211 - FLOUR MILLING",
  "424930 - FLOWER, NURSERY STOCK, AND FLORISTS' SUPPLIES MERCHANT WHOLESALERS",
  "311511 - FLUID MILK MANUFACTURING",
  "333995 - FLUID POWER CYLINDER AND ACTUATOR MANUFACTURING",
  "333996 - FLUID POWER PUMP AND MOTOR MANUFACTURING",
  "332912 - FLUID POWER VALVE AND HOSE FITTING MANUFACTURING",
  "322212 - FOLDING PAPERBOARD BOX MANUFACTURING",
  "456191 - FOOD (HEALTH) SUPPLEMENT RETAILERS",
  "333241 - FOOD PRODUCT MACHINERY MANUFACTURING",
  "722310 - FOOD SERVICE CONTRACTORS",
  "811430 - FOOTWEAR AND LEATHER GOODS REPAIR",
  "316210 - FOOTWEAR MANUFACTURING",
  "424340 - FOOTWEAR MERCHANT WHOLESALERS",
  "113210 - FOREST NURSERIES AND GATHERING OF FOREST PRODUCTS",
  "532281 - FORMAL WEAR AND COSTUME RENTAL",
  "221112 - FOSSIL FUEL ELECTRIC POWER GENERATION",
  "238130 - FRAMING CONTRACTORS",
  "621493 - FREESTANDING AMBULATORY SURGICAL AND EMERGENCY CENTERS",
  "488510 - FREIGHT TRANSPORTATION ARRANGEMENT",
  "424480 - FRESH FRUIT AND VEGETABLE MERCHANT WHOLESALERS",
  "311813 - FROZEN CAKES, PIES, AND OTHER PASTRIES MANUFACTURING",
  "311411 - FROZEN FRUIT, JUICE, AND VEGETABLE MANUFACTURING",
  "311412 - FROZEN SPECIALTY FOOD MANUFACTURING",
  "111336 - FRUIT AND TREE NUT COMBINATION FARMING",
  "311421 - FRUIT AND VEGETABLE CANNING",
  "445230 - FRUIT AND VEGETABLE RETAILERS",
  "457210 - FUEL DEALERS",
  "722511 - FULL-SERVICE RESTAURANTS",
  "812210 - FUNERAL HOMES AND FUNERAL SERVICES",
  "112930 - FUR-BEARING ANIMAL AND RABBIT PRODUCTION",
  "423210 - FURNITURE MERCHANT WHOLESALERS",
  "449110 - FURNITURE RETAILERS",
  "339991 - GASKET, PACKING, AND SEALING DEVICE MANUFACTURING",
  "457110 - GASOLINE STATIONS WITH CONVENIENCE STORES",
  "811111 - GENERAL AUTOMOTIVE REPAIR",
  "484110 - GENERAL FREIGHT TRUCKING, LOCAL",
  "484122 - GENERAL FREIGHT TRUCKING, LONG-DISTANCE, LESS THAN TRUCKLOAD",
  "484121 - GENERAL FREIGHT TRUCKING, LONG-DISTANCE, TRUCKLOAD",
  "424410 - GENERAL LINE GROCERY MERCHANT WHOLESALERS",
  "622110 - GENERAL MEDICAL AND SURGICAL HOSPITALS",
  "532310 - GENERAL RENTAL CENTERS",
  "493110 - GENERAL WAREHOUSING AND STORAGE",
  "541360 - GEOPHYSICAL SURVEYING AND MAPPING SERVICES",
  "221116 - GEOTHERMAL ELECTRIC POWER GENERATION",
  "459420 - GIFT, NOVELTY, AND SOUVENIR RETAILERS",
  "238150 - GLASS AND GLAZING CONTRACTORS",
  "327213 - GLASS CONTAINER MANUFACTURING",
  "327215 - GLASS PRODUCT MANUFACTURING MADE OF PURCHASED GLASS",
  "112420 - GOAT FARMING",
  "212220 - GOLD ORE AND SILVER ORE MINING",
  "713910 - GOLF COURSES AND COUNTRY CLUBS",
  "424510 - GRAIN AND FIELD BEAN MERCHANT WHOLESALERS",
  "813211 - GRANTMAKING FOUNDATIONS",
  "111332 - GRAPE VINEYARDS",
  "541430 - GRAPHIC DESIGN SERVICES",
  "513191 - GREETING CARD PUBLISHERS",
  "327992 - GROUND OR TREATED MINERAL AND EARTH MANUFACTURING",
  "336414 - GUIDED MISSILE AND SPACE VEHICLE MANUFACTURING",
  "336415 - GUIDED MISSILE AND SPACE VEHICLE PROPULSION UNIT AND PROPULSION UNIT PARTS MANUFACTURING",
  "327420 - GYPSUM PRODUCT MANUFACTURING",
  "332510 - HARDWARE MANUFACTURING",
  "423710 - HARDWARE MERCHANT WHOLESALERS",
  "444140 - HARDWARE RETAILERS",
  "321211 - HARDWOOD VENEER AND PLYWOOD MANUFACTURING",
  "111940 - HAY FARMING",
  "562112 - HAZARDOUS WASTE COLLECTION",
  "562211 - HAZARDOUS WASTE TREATMENT AND DISPOSAL",
  "525120 - HEALTH AND WELFARE FUNDS",
  "333414 - HEATING EQUIPMENT (EXCEPT WARM AIR FURNACES) MANUFACTURING",
  "336120 - HEAVY DUTY TRUCK MANUFACTURING",
  "237310 - HIGHWAY, STREET, AND BRIDGE CONSTRUCTION",
  "712120 - HISTORICAL SITES",
  "621491 - HMO MEDICAL CENTERS",
  "459120 - HOBBY, TOY, AND GAME RETAILERS",
  "112210 - HOG AND PIG FARMING",
  "811411 - HOME AND GARDEN EQUIPMENT REPAIR AND MAINTENANCE",
  "444110 - HOME CENTERS",
  "423220 - HOME FURNISHING MERCHANT WHOLESALERS",
  "621610 - HOME HEALTH CARE SERVICES",
  "532283 - HOME HEALTH EQUIPMENT RENTAL",
  "112920 - HORSES AND OTHER EQUINE PRODUCTION",
  "721110 - HOTELS (EXCEPT CASINO HOTELS) AND MOTELS",
  "423620 - HOUSEHOLD APPLIANCES, ELECTRIC HOUSEWARES, AND CONSUMER ELECTRONICS MERCHANT WHOLESALERS",
  "337126 - HOUSEHOLD FURNITURE (EXCEPT WOOD AND UPHOLSTERED) MANUFACTURING",
  "541612 - HUMAN RESOURCES CONSULTING SERVICES",
  "813311 - HUMAN RIGHTS ORGANIZATIONS",
  "114210 - HUNTING AND TRAPPING",
  "221111 - HYDROELECTRIC POWER GENERATION",
  "311520 - ICE CREAM AND FROZEN DESSERT MANUFACTURING",
  "312113 - ICE MANUFACTURING",
  "325413 - IN-VITRO DIAGNOSTIC SUBSTANCE MANUFACTURING",
  "711510 - INDEPENDENT ARTISTS, WRITERS, AND PERFORMERS",
  "541850 - INDOOR AND OUTDOOR DISPLAY ADVERTISING",
  "333413 - INDUSTRIAL AND COMMERCIAL FAN AND BLOWER AND AIR PURIFICATION EQUIPMENT MANUFACTURING",
  "424130 - INDUSTRIAL AND PERSONAL SERVICE PAPER MERCHANT WHOLESALERS",
  "236210 - INDUSTRIAL BUILDING CONSTRUCTION",
  "541420 - INDUSTRIAL DESIGN SERVICES",
  "325120 - INDUSTRIAL GAS MANUFACTURING",
  "812332 - INDUSTRIAL LAUNDERERS",
  "423830 - INDUSTRIAL MACHINERY AND EQUIPMENT MERCHANT WHOLESALERS",
  "333511 - INDUSTRIAL MOLD MANUFACTURING",
  "333994 - INDUSTRIAL PROCESS FURNACE AND OVEN MANUFACTURING",
  "212322 - INDUSTRIAL SAND MINING",
  "423840 - INDUSTRIAL SUPPLIES MERCHANT WHOLESALERS",
  "333924 - INDUSTRIAL TRUCK, TRACTOR, TRAILER, AND STACKER MACHINERY MANUFACTURING",
  "332911 - INDUSTRIAL VALVE MANUFACTURING",
  "483211 - INLAND WATER FREIGHT TRANSPORTATION",
  "483212 - INLAND WATER PASSENGER TRANSPORTATION",
  "337127 - INSTITUTIONAL FURNITURE MANUFACTURING",
  "334515 - INSTRUMENT MANUFACTURING FOR MEASURING AND TESTING ELECTRICITY AND ELECTRICAL SIGNALS",
  "334513 - INSTRUMENTS AND RELATED PRODUCTS MANUFACTURING FOR MEASURING, DISPLAYING, AND CONTROLLING INDUSTRIAL PROCESS VARIABLES",
  "524210 - INSURANCE AGENCIES AND BROKERAGES",
  "541410 - INTERIOR DESIGN SERVICES",
  "928120 - INTERNATIONAL AFFAIRS",
  "522299 - INTERNATIONAL, SECONDARY MARKET, AND ALL OTHER NON-DEPOSITORY CREDIT INTERMEDIATION",
  "485210 - INTERURBAN AND RURAL BUS TRANSPORTATION",
  "561611 - INVESTIGATION AND PERSONAL BACKGROUND CHECK SERVICES",
  "523150 - INVESTMENT BANKING AND SECURITIES INTERMEDIATION",
  "332111 - IRON AND STEEL FORGING",
  "331110 - IRON AND STEEL MILLS AND FERROALLOY MANUFACTURING",
  "331210 - IRON AND STEEL PIPE AND TUBE MANUFACTURING FROM PURCHASED STEEL",
  "331511 - IRON FOUNDRIES",
  "212210 - IRON ORE MINING",
  "334517 - IRRADIATION APPARATUS MANUFACTURING",
  "561720 - JANITORIAL SERVICES",
  "339910 - JEWELRY AND SILVERWARE MANUFACTURING",
  "458310 - JEWELRY RETAILERS",
  "423940 - JEWELRY, WATCH, PRECIOUS STONE, AND PRECIOUS METAL MERCHANT WHOLESALERS",
  "611210 - JUNIOR COLLEGES",
  "212323 - KAOLIN, CLAY, AND CERAMIC AND REFRACTORY MINERALS MINING",
  "621492 - KIDNEY DIALYSIS CENTERS",
  "313240 - KNIT FABRIC MILLS",
  "813930 - LABOR UNIONS AND SIMILAR LABOR ORGANIZATIONS",
  "326130 - LAMINATED PLASTICS PLATE, SHEET (EXCEPT PACKAGING), AND SHAPE MANUFACTURING",
  "237210 - LAND SUBDIVISION",
  "541320 - LANDSCAPE ARCHITECTURAL SERVICES",
  "561730 - LANDSCAPING SERVICES",
  "611630 - LANGUAGE SCHOOLS",
  "333112 - LAWN AND GARDEN TRACTOR AND HOME LAWN AND GARDEN EQUIPMENT MANUFACTURING",
  "316110 - LEATHER AND HIDE TANNING AND FINISHING",
  "922130 - LEGAL COUNSEL AND PROSECUTION",
  "921120 - LEGISLATIVE BODIES",
  "531130 - LESSORS OF MINI WAREHOUSES AND SELF-STORAGE UNITS",
  "533110 - LESSORS OF NONFINANCIAL INTANGIBLE ASSETS (EXCEPT COPYRIGHTED WORKS)",
  "531120 - LESSORS OF NONRESIDENTIAL BUILDINGS (EXCEPT MINI-WAREHOUSES)",
  "531190 - LESSORS OF OTHER REAL ESTATE PROPERTY",
  "531110 - LESSORS OF RESIDENTIAL BUILDINGS AND DWELLINGS",
  "519210 - LIBRARIES AND ARCHIVES",
  "327410 - LIME MANUFACTURING",
  "722513 - LIMITED-SERVICE RESTAURANTS",
  "485320 - LIMOUSINE SERVICE",
  "482111 - LINE-HAUL RAILROADS",
  "812331 - LINEN SUPPLY",
  "424520 - LIVESTOCK MERCHANT WHOLESALERS",
  "492210 - LOCAL MESSENGERS AND LOCAL DELIVERY",
  "561622 - LOCKSMITHS",
  "113310 - LOGGING",
  "458320 - LUGGAGE AND LEATHER GOODS RETAILERS",
  "423310 - LUMBER, PLYWOOD, MILLWORK, AND WOOD PANEL MERCHANT WHOLESALERS",
  "332710 - MACHINE SHOPS",
  "333517 - MACHINE TOOL MANUFACTURING",
  "335220 - MAJOR HOUSEHOLD APPLIANCE MANUFACTURING",
  "311213 - MALT MANUFACTURING",
  "459930 - MANUFACTURED (MOBILE) HOME DEALERS",
  "321991 - MANUFACTURED HOME (MOBILE HOME) MANUFACTURING",
  "334610 - MANUFACTURING AND REPRODUCING MAGNETIC AND OPTICAL MEDIA",
  "713930 - MARINAS",
  "488320 - MARINE CARGO HANDLING",
  "541613 - MARKETING CONSULTING SERVICES",
  "541910 - MARKETING RESEARCH AND PUBLIC OPINION POLLING",
  "238140 - MASONRY CONTRACTORS",
  "562920 - MATERIALS RECOVERY FACILITIES",
  "337910 - MATTRESS MANUFACTURING",
  "311941 - MAYONNAISE, DRESSING, AND OTHER PREPARED SAUCE MANUFACTURING",
  "333914 - MEASURING, DISPENSING, AND OTHER PUMPING EQUIPMENT MANUFACTURING",
  "424470 - MEAT AND MEAT PRODUCT MERCHANT WHOLESALERS",
  "311612 - MEAT PROCESSED FROM CARCASSES",
  "445240 - MEAT RETAILERS",
  "333613 - MECHANICAL POWER TRANSMISSION EQUIPMENT MANUFACTURING",
  "541830 - MEDIA BUYING AGENCIES",
  "541840 - MEDIA REPRESENTATIVES",
  "516210 - MEDIA STREAMING DISTRIBUTION SERVICES, SOCIAL NETWORKS, AND OTHER MEDIA NETWORKS AND CONTENT PROVIDERS",
  "621511 - MEDICAL LABORATORIES",
  "423450 - MEDICAL, DENTAL, AND HOSPITAL EQUIPMENT AND SUPPLIES MERCHANT WHOLESALERS",
  "325411 - MEDICINAL AND BOTANICAL MANUFACTURING",
  "332431 - METAL CAN MANUFACTURING",
  "332812 - METAL COATING, ENGRAVING (EXCEPT JEWELRY AND SILVERWARE), AND ALLIED SERVICES TO MANUFACTURERS",
  "332119 - METAL CROWN, CLOSURE, AND OTHER METAL STAMPING (EXCEPT AUTOMOTIVE)",
  "332811 - METAL HEAT TREATING",
  "332215 - METAL KITCHEN COOKWARE, UTENSIL, CUTLERY, AND FLATWARE (EXCEPT PRECIOUS) MANUFACTURING",
  "423510 - METAL SERVICE CENTERS AND OTHER METAL MERCHANT WHOLESALERS",
  "332420 - METAL TANK (HEAVY GAUGE) MANUFACTURING",
  "332321 - METAL WINDOW AND DOOR MANUFACTURING",
  "336992 - MILITARY ARMORED VEHICLE, TANK, AND TANK COMPONENT MANUFACTURING",
  "327993 - MINERAL WOOL MANUFACTURING",
  "333131 - MINING MACHINERY AND EQUIPMENT MANUFACTURING",
  "523999 - MISCELLANEOUS FINANCIAL INVESTMENT ACTIVITIES",
  "523910 - MISCELLANEOUS INTERMEDIATION",
  "485111 - MIXED MODE TRANSIT SYSTEMS",
  "722330 - MOBILE FOOD SERVICES",
  "521110 - MONETARY AUTHORITIES-CENTRAL BANK",
  "522310 - MORTGAGE AND NONMORTGAGE LOAN BROKERS",
  "512120 - MOTION PICTURE AND VIDEO DISTRIBUTION",
  "512110 - MOTION PICTURE AND VIDEO PRODUCTION",
  "512131 - MOTION PICTURE THEATERS (EXCEPT DRIVE-INS)",
  "335312 - MOTOR AND GENERATOR MANUFACTURING",
  "336213 - MOTOR HOME MANUFACTURING",
  "336211 - MOTOR VEHICLE BODY MANUFACTURING",
  "336340 - MOTOR VEHICLE BRAKE SYSTEM MANUFACTURING",
  "336320 - MOTOR VEHICLE ELECTRICAL AND ELECTRONIC EQUIPMENT MANUFACTURING",
  "336310 - MOTOR VEHICLE GASOLINE ENGINE AND ENGINE PARTS MANUFACTURING",
  "336370 - MOTOR VEHICLE METAL STAMPING",
  "423140 - MOTOR VEHICLE PARTS (USED) MERCHANT WHOLESALERS",
  "336360 - MOTOR VEHICLE SEATING AND INTERIOR TRIM MANUFACTURING",
  "336330 - MOTOR VEHICLE STEERING AND SUSPENSION COMPONENTS (EXCEPT SPRING) MANUFACTURING",
  "423120 - MOTOR VEHICLE SUPPLIES AND NEW PARTS MERCHANT WHOLESALERS",
  "488410 - MOTOR VEHICLE TOWING",
  "336350 - MOTOR VEHICLE TRANSMISSION AND POWER TRAIN PARTS MANUFACTURING",
  "441227 - MOTORCYCLE, ATV, AND ALL OTHER MOTOR VEHICLE DEALERS",
  "336991 - MOTORCYCLE, BICYCLE, AND PARTS MANUFACTURING",
  "712110 - MUSEUMS",
  "111411 - MUSHROOM PRODUCTION",
  "512230 - MUSIC PUBLISHERS",
  "711130 - MUSICAL GROUPS AND ARTISTS",
  "459140 - MUSICAL INSTRUMENT AND SUPPLIES RETAILERS",
  "339992 - MUSICAL INSTRUMENT MANUFACTURING",
  "812113 - NAIL SALONS",
  "313220 - NARROW FABRIC MILLS AND SCHIFFLI MACHINE EMBROIDERY",
  "928110 - NATIONAL SECURITY",
  "221210 - NATURAL GAS DISTRIBUTION",
  "211130 - NATURAL GAS EXTRACTION",
  "712190 - NATURE PARKS AND OTHER SIMILAR INSTITUTIONS",
  "488330 - NAVIGATIONAL SERVICES TO SHIPPING",
  "441110 - NEW CAR DEALERS",
  "236117 - NEW HOUSING FOR-SALE BUILDERS",
  "236116 - NEW MULTIFAMILY HOUSING CONSTRUCTION (EXCEPT FOR-SALE BUILDERS)",
  "236115 - NEW SINGLE-FAMILY HOUSING CONSTRUCTION (EXCEPT FOR-SALE BUILDERS)",
  "513110 - NEWSPAPER PUBLISHERS",
  "325311 - NITROGENOUS FERTILIZER MANUFACTURING",
  "311340 - NON-CHOCOLATE CONFECTIONERY MANUFACTURING",
  "332112 - NON-FERROUS FORGING",
  "331410 - NON-FERROUS METAL (EXCEPT ALUMINUM) SMELTING AND REFINING",
  "331491 - NON-FERROUS METAL (EXCEPT COPPER AND ALUMINUM) ROLLING, DRAWING, AND EXTRUDING",
  "331523 - NON-FERROUS METAL DIE-CASTING FOUNDRIES",
  "481212 - NON-SCHEDULED CHARTERED FREIGHT AIR TRANSPORTATION",
  "481211 - NON-SCHEDULED CHARTERED PASSENGER AIR TRANSPORTATION",
  "337122 - NON-UPHOLSTERED WOOD HOUSEHOLD FURNITURE MANUFACTURING",
  "335932 - NONCURRENT-CARRYING WIRING DEVICE MANUFACTURING",
  "531312 - NONRESIDENTIAL PROPERTY MANAGERS",
  "313230 - NONWOVEN FABRIC MILLS",
  "221113 - NUCLEAR ELECTRIC POWER GENERATION",
  "111421 - NURSERY AND TREE PRODUCTION",
  "444240 - NURSERY, GARDEN CENTER, AND FARM SUPPLY RETAILERS",
  "623110 - NURSING CARE FACILITIES (SKILLED NURSING FACILITIES)",
  "561110 - OFFICE ADMINISTRATIVE SERVICES",
  "423420 - OFFICE EQUIPMENT MERCHANT WHOLESALERS",
  "337214 - OFFICE FURNITURE (EXCEPT WOOD) MANUFACTURING",
  "532420 - OFFICE MACHINERY AND EQUIPMENT RENTAL AND LEASING",
  "339940 - OFFICE SUPPLIES (EXCEPT PAPER) MANUFACTURING",
  "459410 - OFFICE SUPPLIES AND STATIONERY RETAILERS",
  "621399 - OFFICES OF ALL OTHER MISCELLANEOUS HEALTH PRACTITIONERS",
  "551111 - OFFICES OF BANK HOLDING COMPANIES",
  "541211 - OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS",
  "621310 - OFFICES OF CHIROPRACTORS",
  "621210 - OFFICES OF DENTISTS",
  "541110 - OFFICES OF LAWYERS",
  "621330 - OFFICES OF MENTAL HEALTH PRACTITIONERS (EXCEPT PHYSICIANS)",
  "541120 - OFFICES OF NOTARIES",
  "621320 - OFFICES OF OPTOMETRISTS",
  "551112 - OFFICES OF OTHER HOLDING COMPANIES",
  "621340 - OFFICES OF PHYSICAL, OCCUPATIONAL AND SPEECH THERAPISTS, AND AUDIOLOGISTS",
  "621111 - OFFICES OF PHYSICIANS (EXCEPT MENTAL HEALTH SPECIALISTS)",
  "621112 - OFFICES OF PHYSICIANS, MENTAL HEALTH SPECIALISTS",
  "621391 - OFFICES OF PODIATRISTS",
  "531210 - OFFICES OF REAL ESTATE AGENTS AND BROKERS",
  "531320 - OFFICES OF REAL ESTATE APPRAISERS",
  "333132 - OIL AND GAS FIELD MACHINERY AND EQUIPMENT MANUFACTURING",
  "237120 - OIL AND GAS PIPELINE AND RELATED STRUCTURES CONSTRUCTION",
  "111120 - OILSEED (EXCEPT SOYBEAN) FARMING",
  "111191 - OILSEED AND GRAIN COMBINATION FARMING",
  "812922 - ONE-HOUR PHOTO FINISHING",
  "525910 - OPEN-END INVESTMENT FUNDS",
  "339115 - OPHTHALMIC GOODS MANUFACTURING",
  "423460 - OPHTHALMIC GOODS MERCHANT WHOLESALERS",
  "456130 - OPTICAL GOODS RETAILERS",
  "111310 - ORANGE GROVES",
  "332323 - ORNAMENTAL AND ARCHITECTURAL METAL WORK MANUFACTURING",
  "541219 - OTHER ACCOUNTING SERVICES",
  "522390 - OTHER ACTIVITIES RELATED TO CREDIT INTERMEDIATION",
  "531390 - OTHER ACTIVITIES RELATED TO REAL ESTATE",
  "336413 - OTHER AIRCRAFT PARTS AND AUXILIARY EQUIPMENT MANUFACTURING",
  "488119 - OTHER AIRPORT OPERATIONS",
  "331318 - OTHER ALUMINUM ROLLING, DRAWING, AND EXTRUDING",
  "311119 - OTHER ANIMAL FOOD MANUFACTURING",
  "112519 - OTHER AQUACULTURE",
  "325180 - OTHER BASIC INORGANIC CHEMICAL MANUFACTURING",
  "238290 - OTHER BUILDING EQUIPMENT CONTRACTORS",
  "238390 - OTHER BUILDING FINISHING CONTRACTORS",
  "444180 - OTHER BUILDING MATERIAL DEALERS",
  "561439 - OTHER BUSINESS SERVICE CENTERS (INCLUDING COPY SHOPS)",
  "424690 - OTHER CHEMICAL AND ALLIED PRODUCTS MERCHANT WHOLESALERS",
  "532490 - OTHER COMMERCIAL AND INDUSTRIAL MACHINERY AND EQUIPMENT RENTAL AND LEASING",
  "423440 - OTHER COMMERCIAL EQUIPMENT MERCHANT WHOLESALERS",
  "335929 - OTHER COMMUNICATION AND ENERGY WIRE MANUFACTURING",
  "334290 - OTHER COMMUNICATIONS EQUIPMENT MANUFACTURING",
  "624229 - OTHER COMMUNITY HOUSING SERVICES",
  "541519 - OTHER COMPUTER RELATED SERVICES",
  "327390 - OTHER CONCRETE PRODUCT MANUFACTURING",
  "423390 - OTHER CONSTRUCTION MATERIAL MERCHANT WHOLESALERS",
  "212319 - OTHER CRUSHED AND BROKEN STONE MINING AND QUARRYING",
  "524128 - OTHER DIRECT INSURANCE (EXCEPT LIFE, HEALTH, AND MEDICAL) CARRIERS",
  "221118 - OTHER ELECTRIC POWER GENERATION",
  "334419 - OTHER ELECTRONIC COMPONENT MANUFACTURING",
  "423690 - OTHER ELECTRONIC PARTS AND EQUIPMENT MERCHANT WHOLESALERS",
  "333618 - OTHER ENGINE EQUIPMENT MANUFACTURING",
  "332618 - OTHER FABRICATED WIRE PRODUCT MANUFACTURING",
  "424590 - OTHER FARM PRODUCT RAW MATERIAL MERCHANT WHOLESALERS",
  "525990 - OTHER FINANCIAL VEHICLES",
  "111419 - OTHER FOOD CROPS GROWN UNDER COVER",
  "238190 - OTHER FOUNDATION, STRUCTURE, AND BUILDING EXTERIOR CONTRACTORS",
  "713290 - OTHER GAMBLING INDUSTRIES",
  "457120 - OTHER GASOLINE STATIONS",
  "921190 - OTHER GENERAL GOVERNMENT SUPPORT",
  "813219 - OTHER GRANTMAKING AND GIVING SERVICES",
  "424490 - OTHER GROCERY AND RELATED PRODUCTS MERCHANT WHOLESALERS",
  "336419 - OTHER GUIDED MISSILE AND SPACE VEHICLE PARTS AND AUXILIARY EQUIPMENT MANUFACTURING",
  "237990 - OTHER HEAVY AND CIVIL ENGINEERING CONSTRUCTION",
  "624190 - OTHER INDIVIDUAL AND FAMILY SERVICES",
  "525190 - OTHER INSURANCE FUNDS",
  "922190 - OTHER JUSTICE, PUBLIC ORDER, AND SAFETY ACTIVITIES",
  "316990 - OTHER LEATHER AND ALLIED PRODUCT MANUFACTURING",
  "541618 - OTHER MANAGEMENT CONSULTING SERVICES",
  "114119 - OTHER MARINE FISHING",
  "334519 - OTHER MEASURING AND CONTROLLING DEVICE MANUFACTURING",
  "332439 - OTHER METAL CONTAINER MANUFACTURING",
  "212290 - OTHER METAL ORE MINING",
  "332919 - OTHER METAL VALVE AND PIPE FITTING MANUFACTURING",
  "321918 - OTHER MILLWORK (INCLUDING FLOORING)",
  "423990 - OTHER MISCELLANEOUS DURABLE GOODS MERCHANT WHOLESALERS",
  "424990 - OTHER MISCELLANEOUS NONDURABLE GOODS MERCHANT WHOLESALERS",
  "512199 - OTHER MOTION PICTURE AND VIDEO INDUSTRIES",
  "336390 - OTHER MOTOR VEHICLE PARTS MANUFACTURING",
  "111339 - OTHER NON-CITRUS FRUIT FARMING",
  "331529 - OTHER NON-FERROUS METAL FOUNDRIES (EXCEPT DIE-CASTING)",
  "562219 - OTHER NON-HAZARDOUS WASTE TREATMENT AND DISPOSAL",
  "481219 - OTHER NON-SCHEDULED AIR TRANSPORTATION",
  "212390 - OTHER NONMETALLIC MINERAL MINING AND QUARRYING",
  "322219 - OTHER PAPERBOARD CONTAINER MANUFACTURING",
  "711190 - OTHER PERFORMING ARTS COMPANIES",
  "811490 - OTHER PERSONAL AND HOUSEHOLD GOODS REPAIR AND MAINTENANCE",
  "812199 - OTHER PERSONAL CARE SERVICES",
  "112390 - OTHER POULTRY PRODUCTION",
  "327212 - OTHER PRESSED AND BLOWN GLASS AND GLASSWARE MANUFACTURING",
  "423490 - OTHER PROFESSIONAL EQUIPMENT AND SUPPLIES MERCHANT WHOLESALERS",
  "623990 - OTHER RESIDENTIAL CARE FACILITIES",
  "541690 - OTHER SCIENTIFIC AND TECHNICAL CONSULTING SERVICES",
  "541890 - OTHER SERVICES RELATED TO ADVERTISING",
  "561790 - OTHER SERVICES TO BUILDINGS AND DWELLINGS",
  "813990 - OTHER SIMILAR ORGANIZATIONS (EXCEPT BUSINESS, PROFESSIONAL, LABOR, AND POLITICAL ORGANIZATIONS)",
  "311919 - OTHER SNACK FOOD MANUFACTURING",
  "813319 - OTHER SOCIAL ADVOCACY ORGANIZATIONS",
  "512290 - OTHER SOUND RECORDING INDUSTRIES",
  "541490 - OTHER SPECIALIZED DESIGN SERVICES",
  "711219 - OTHER SPECTATOR SPORTS",
  "488190 - OTHER SUPPORT ACTIVITIES FOR AIR TRANSPORTATION",
  "488490 - OTHER SUPPORT ACTIVITIES FOR ROAD TRANSPORTATION",
  "488390 - OTHER SUPPORT ACTIVITIES FOR WATER TRANSPORTATION",
  "611519 - OTHER TECHNICAL AND TRADE SCHOOLS",
  "485119 - OTHER URBAN TRANSIT SYSTEMS",
  "111219 - OTHER VEGETABLE (EXCEPT POTATO) AND MELON FARMING",
  "493190 - OTHER WAREHOUSING AND STORAGE",
  "562119 - OTHER WASTE COLLECTION",
  "444230 - OUTDOOR POWER EQUIPMENT RETAILERS",
  "621420 - OUTPATIENT MENTAL HEALTH AND SUBSTANCE ABUSE CENTERS",
  "333923 - OVERHEAD TRAVELING CRANE, HOIST, AND MONORAIL SYSTEM MANUFACTURING",
  "424420 - PACKAGED FROZEN FOOD MERCHANT WHOLESALERS",
  "561910 - PACKAGING AND LABELING SERVICES",
  "333993 - PACKAGING MACHINERY MANUFACTURING",
  "488991 - PACKING AND CRATING",
  "325510 - PAINT AND COATING MANUFACTURING",
  "444120 - PAINT AND WALLPAPER RETAILERS",
  "424950 - PAINT, VARNISH, AND SUPPLIES MERCHANT WHOLESALERS",
  "238320 - PAINTING AND WALL COVERING CONTRACTORS",
  "322220 - PAPER BAG AND COATED AND TREATED PAPER MANUFACTURING",
  "322120 - PAPER MILLS",
  "322130 - PAPERBOARD MILLS",
  "812930 - PARKING LOTS AND GARAGES",
  "922150 - PAROLE OFFICES AND PROBATION OFFICES",
  "532112 - PASSENGER CAR LEASING",
  "532111 - PASSENGER CAR RENTAL",
  "541214 - PAYROLL SERVICES",
  "111992 - PEANUT FARMING",
  "525110 - PENSION FUNDS",
  "513120 - PERIODICAL PUBLISHERS",
  "311991 - PERISHABLE PREPARED FOOD MANUFACTURING",
  "325320 - PESTICIDE AND OTHER AGRICULTURAL CHEMICAL MANUFACTURING",
  "459910 - PET AND PET SUPPLIES RETAILERS",
  "812910 - PET CARE (EXCEPT VETERINARY) SERVICES",
  "325110 - PETROCHEMICAL MANUFACTURING",
  "424720 - PETROLEUM AND PETROLEUM PRODUCTS MERCHANT WHOLESALERS (EXCEPT BULK STATIONS AND TERMINALS)",
  "424710 - PETROLEUM BULK STATIONS AND TERMINALS",
  "324191 - PETROLEUM LUBRICATING OIL AND GREASE MANUFACTURING",
  "324110 - PETROLEUM REFINERIES",
  "325412 - PHARMACEUTICAL PREPARATION MANUFACTURING",
  "456110 - PHARMACIES AND DRUG RETAILERS",
  "524292 - PHARMACY BENEFIT MANAGEMENT AND OTHER THIRD PARTY ADMINISTRATION OF INSURANCE AND PENSION FUNDS",
  "325312 - PHOSPHATIC FERTILIZER MANUFACTURING",
  "812921 - PHOTOFINISHING LABORATORIES (EXCEPT ONE-HOUR)",
  "423410 - PHOTOGRAPHIC EQUIPMENT AND SUPPLIES MERCHANT WHOLESALERS",
  "325992 - PHOTOGRAPHIC FILM, PAPER, PLATE, CHEMICAL, AND COPY TONER MANUFACTURING",
  "541921 - PHOTOGRAPHY STUDIOS, PORTRAIT",
  "424310 - PIECE GOODS, NOTIONS, AND OTHER DRY GOODS MERCHANT WHOLESALERS",
  "486110 - PIPELINE TRANSPORTATION OF CRUDE OIL",
  "486210 - PIPELINE TRANSPORTATION OF NATURAL GAS",
  "486910 - PIPELINE TRANSPORTATION OF REFINED PETROLEUM PRODUCTS",
  "326111 - PLASTICS BAG AND POUCH MANUFACTURING",
  "326160 - PLASTICS BOTTLE MANUFACTURING",
  "325211 - PLASTICS MATERIAL AND RESIN MANUFACTURING",
  "424610 - PLASTICS MATERIALS AND BASIC FORMS AND SHAPES MERCHANT WHOLESALERS",
  "326112 - PLASTICS PACKAGING FILM AND SHEET (INCLUDING LAMINATED) MANUFACTURING",
  "326122 - PLASTICS PIPE AND PIPE FITTING MANUFACTURING",
  "326191 - PLASTICS PLUMBING FIXTURE MANUFACTURING",
  "332313 - PLATE WORK MANUFACTURING",
  "423720 - PLUMBING AND HEATING EQUIPMENT AND SUPPLIES (HYDRONICS) MERCHANT WHOLESALERS",
  "332913 - PLUMBING FIXTURE FITTING AND TRIM MANUFACTURING",
  "238220 - PLUMBING, HEATING, AND AIR-CONDITIONING CONTRACTORS",
  "922120 - POLICE PROTECTION",
  "325612 - POLISH AND OTHER SANITATION GOOD MANUFACTURING",
  "813940 - POLITICAL ORGANIZATIONS",
  "326140 - POLYSTYRENE FOAM PRODUCT MANUFACTURING",
  "488310 - PORT AND HARBOR OPERATIONS",
  "523940 - PORTFOLIO MANAGEMENT AND INVESTMENT ADVICE",
  "491110 - POSTAL SERVICE",
  "115114 - POSTHARVEST CROP ACTIVITIES (EXCEPT COTTON GINNING)",
  "111211 - POTATO FARMING",
  "327110 - POTTERY, CERAMICS, AND PLUMBING FIXTURE MANUFACTURING",
  "424440 - POULTRY AND POULTRY PRODUCT MERCHANT WHOLESALERS",
  "112340 - POULTRY HATCHERIES",
  "311615 - POULTRY PROCESSING",
  "238110 - POURED CONCRETE FOUNDATION AND STRUCTURE CONTRACTORS",
  "332117 - POWDER METALLURGY PART MANUFACTURING",
  "237130 - POWER AND COMMUNICATION LINE AND RELATED STRUCTURES CONSTRUCTION",
  "332410 - POWER BOILER AND HEAT EXCHANGER MANUFACTURING",
  "333991 - POWER-DRIVEN HAND TOOL MANUFACTURING",
  "335311 - POWER, DISTRIBUTION, AND SPECIALTY TRANSFORMER MANUFACTURING",
  "332721 - PRECISION TURNED PRODUCT MANUFACTURING",
  "332311 - PREFABRICATED METAL BUILDING AND COMPONENT MANUFACTURING",
  "321992 - PREFABRICATED WOOD BUILDING MANUFACTURING",
  "334418 - PRINTED CIRCUIT ASSEMBLY (ELECTRONIC ASSEMBLY) MANUFACTURING",
  "424110 - PRINTING AND WRITING PAPER MERCHANT WHOLESALERS",
  "325910 - PRINTING INK MANUFACTURING",
  "814110 - PRIVATE HOUSEHOLDS",
  "561431 - PRIVATE MAIL CENTERS",
  "541614 - PROCESS, PHYSICAL DISTRIBUTION, AND LOGISTICS CONSULTING SERVICES",
  "611430 - PROFESSIONAL AND MANAGEMENT DEVELOPMENT TRAINING",
  "561330 - PROFESSIONAL EMPLOYER ORGANIZATIONS",
  "813920 - PROFESSIONAL ORGANIZATIONS",
  "711310 - PROMOTERS OF PERFORMING ARTS, SPORTS, AND SIMILAR EVENTS WITH FACILITIES",
  "711320 - PROMOTERS OF PERFORMING ARTS, SPORTS, AND SIMILAR EVENTS WITHOUT FACILITIES",
  "622210 - PSYCHIATRIC AND SUBSTANCE ABUSE HOSPITALS",
  "921130 - PUBLIC FINANCE ACTIVITIES",
  "541820 - PUBLIC RELATIONS AGENCIES",
  "322110 - PULP MILLS",
  "711212 - RACETRACKS",
  "334220 - RADIO AND TELEVISION BROADCASTING AND WIRELESS COMMUNICATIONS EQUIPMENT MANUFACTURING",
  "516110 - RADIO BROADCASTING STATIONS",
  "336510 - RAILROAD ROLLING STOCK MANUFACTURING",
  "327320 - READY-MIX CONCRETE MANUFACTURING",
  "522292 - REAL ESTATE CREDIT",
  "321219 - RECONSTITUTED WOOD PRODUCT MANUFACTURING",
  "512250 - RECORD PRODUCTION AND DISTRIBUTION",
  "721214 - RECREATIONAL AND VACATION CAMPS (EXCEPT CAMPGROUNDS)",
  "532284 - RECREATIONAL GOODS RENTAL",
  "441210 - RECREATIONAL VEHICLE DEALERS",
  "423930 - RECYCLABLE MATERIAL MERCHANT WHOLESALERS",
  "493120 - REFRIGERATED WAREHOUSING AND STORAGE",
  "423740 - REFRIGERATION EQUIPMENT AND SUPPLIES MERCHANT WHOLESALERS",
  "926130 - REGULATION AND ADMINISTRATION OF COMMUNICATIONS, ELECTRIC, GAS, AND OTHER UTILITIES",
  "926120 - REGULATION AND ADMINISTRATION OF TRANSPORTATION PROGRAMS",
  "926140 - REGULATION OF AGRICULTURAL MARKETING AND COMMODITIES",
  "926150 - REGULATION, LICENSING, AND INSPECTION OF MISCELLANEOUS COMMERCIAL SECTORS",
  "524130 - REINSURANCE CARRIERS",
  "335314 - RELAY AND INDUSTRIAL CONTROL MANUFACTURING",
  "813110 - RELIGIOUS ORGANIZATIONS",
  "562910 - REMEDIATION SERVICES",
  "311613 - RENDERING AND MEAT BYPRODUCT PROCESSING",
  "561491 - REPOSSESSION SERVICES",
  "541714 - RESEARCH AND DEVELOPMENT IN BIOTECHNOLOGY (EXCEPT NANOBIOTECHNOLOGY)",
  "541713 - RESEARCH AND DEVELOPMENT IN NANOTECHNOLOGY",
  "541715 - RESEARCH AND DEVELOPMENT IN THE PHYSICAL, ENGINEERING, AND LIFE SCIENCES (EXCEPT NANOTECHNOLOGY AND BIOTECHNOLOGY)",
  "541720 - RESEARCH AND DEVELOPMENT IN THE SOCIAL SCIENCES AND HUMANITIES",
  "335131 - RESIDENTIAL ELECTRIC LIGHTING FIXTURE MANUFACTURING",
  "623210 - RESIDENTIAL INTELLECTUAL AND DEVELOPMENTAL DISABILITY FACILITIES",
  "623220 - RESIDENTIAL MENTAL HEALTH AND SUBSTANCE ABUSE FACILITIES",
  "531311 - RESIDENTIAL PROPERTY MANAGERS",
  "236118 - RESIDENTIAL REMODELERS",
  "311811 - RETAIL BAKERIES",
  "722515 - RETAIL ICE CREAM STORE",
  "811420 - REUPHOLSTERY AND FURNITURE REPAIR",
  "111160 - RICE FARMING",
  "311212 - RICE MILLING",
  "311911 - ROASTED NUTS AND PEANUT BUTTER MANUFACTURING",
  "331221 - ROLLED STEEL SHAPE MANUFACTURING",
  "333519 - ROLLING MILL AND OTHER METALWORKING MACHINERY MANUFACTURING",
  "238160 - ROOFING CONTRACTORS",
  "423330 - ROOFING, SIDING, AND INSULATION MATERIAL MERCHANT WHOLESALERS",
  "721310 - ROOMING AND BOARDING HOUSES, DORMITORIES, AND WORKERS' CAMPS",
  "314994 - ROPE, CORDAGE, TWINE, TIRE CORD, AND TIRE FABRIC MILLS",
  "326220 - RUBBER AND PLASTICS HOSES AND BELTING MANUFACTURING",
  "326291 - RUBBER PRODUCT MANUFACTURING FOR MECHANICAL USE",
  "721211 - RV (RECREATIONAL VEHICLE) PARKS AND CAMPGROUNDS",
  "522220 - SALES FINANCING",
  "322291 - SANITARY PAPER PRODUCT MANUFACTURING",
  "517410 - SATELLITE TELECOMMUNICATIONS",
  "522180 - SAVINGS INSTITUTIONS AND OTHER DEPOSITORY CREDIT INTERMEDIATION",
  "332216 - SAW BLADE AND HAND TOOL MANUFACTURING",
  "333243 - SAWMILL, WOODWORKING, AND PAPER MACHINERY MANUFACTURING",
  "321113 - SAWMILLS",
  "487110 - SCENIC AND SIGHTSEEING TRANSPORTATION, LAND",
  "487990 - SCENIC AND SIGHTSEEING TRANSPORTATION, OTHER",
  "487210 - SCENIC AND SIGHTSEEING TRANSPORTATION, WATER",
  "481112 - SCHEDULED FREIGHT AIR TRANSPORTATION",
  "481111 - SCHEDULED PASSENGER AIR TRANSPORTATION",
  "485410 - SCHOOL AND EMPLOYEE BUS TRANSPORTATION",
  "311710 - SEAFOOD PRODUCT PREPARATION AND PACKAGING",
  "334511 - SEARCH, DETECTION, NAVIGATION, GUIDANCE, AERONAUTICAL, AND NAUTICAL SYSTEM AND INSTRUMENT MANUFACTURING",
  "331314 - SECONDARY SMELTING AND ALLOYING OF ALUMINUM",
  "331492 - SECONDARY SMELTING, REFINING, AND ALLOYING OF NON-FERROUS METAL (EXCEPT COPPER AND ALUMINUM)",
  "523210 - SECURITIES AND COMMODITY EXCHANGES",
  "561612 - SECURITY GUARDS AND PATROL SERVICES",
  "561621 - SECURITY SYSTEMS SERVICES (EXCEPT LOCKSMITHS)",
  "334413 - SEMICONDUCTOR AND RELATED DEVICE MANUFACTURING",
  "333242 - SEMICONDUCTOR MACHINERY MANUFACTURING",
  "562991 - SEPTIC TANK AND RELATED SERVICES",
  "423850 - SERVICE ESTABLISHMENT EQUIPMENT AND SUPPLIES MERCHANT WHOLESALERS",
  "624120 - SERVICES FOR THE ELDERLY AND PERSONS WITH DISABILITIES",
  "221320 - SEWAGE TREATMENT FACILITIES",
  "459130 - SEWING, NEEDLEWORK, AND PIECE GOODS RETAILERS",
  "112410 - SHEEP FARMING",
  "332322 - SHEET METAL WORK MANUFACTURING",
  "112512 - SHELLFISH FARMING",
  "114112 - SHELLFISH FISHING",
  "336611 - SHIP BUILDING AND REPAIRING",
  "458210 - SHOE RETAILERS",
  "482112 - SHORT LINE RAILROADS",
  "337215 - SHOWCASE, PARTITION, SHELVING, AND LOCKER MANUFACTURING",
  "238170 - SIDING CONTRACTORS",
  "339950 - SIGN MANUFACTURING",
  "238910 - SITE PREPARATION CONTRACTORS",
  "713920 - SKIING FACILITIES",
  "332992 - SMALL ARMS AMMUNITION MANUFACTURING",
  "332994 - SMALL ARMS, ORDNANCE, AND ORDNANCE ACCESSORIES MANUFACTURING",
  "335210 - SMALL ELECTRICAL APPLIANCE MANUFACTURING",
  "722515 - SNACK AND NONALCOHOLIC BEVERAGE BARS",
  "325611 - SOAP AND OTHER DETERGENT MANUFACTURING",
  "312111 - SOFT DRINK MANUFACTURING",
  "513210 - SOFTWARE PUBLISHERS",
  "321212 - SOFTWOOD VENEER AND PLYWOOD MANUFACTURING",
  "115112 - SOIL PREPARATION, PLANTING, AND CULTIVATING",
  "221114 - SOLAR ELECTRIC POWER GENERATION",
  "562111 - SOLID WASTE COLLECTION",
  "562213 - SOLID WASTE COMBUSTORS AND INCINERATORS",
  "562212 - SOLID WASTE LANDFILL",
  "512240 - SOUND RECORDING STUDIOS",
  "311224 - SOYBEAN AND OTHER OILSEED PROCESSING",
  "111110 - SOYBEAN FARMING",
  "927110 - SPACE RESEARCH AND TECHNOLOGY",
  "333514 - SPECIAL DIE AND TOOL, DIE SET, JIG, AND FIXTURE MANUFACTURING",
  "485991 - SPECIAL NEEDS TRANSPORTATION",
  "811114 - SPECIALIZED AUTOMOTIVE REPAIR",
  "484220 - SPECIALIZED FREIGHT (EXCEPT USED GOODS) TRUCKING, LOCAL",
  "484230 - SPECIALIZED FREIGHT (EXCEPT USED GOODS) TRUCKING, LONG-DISTANCE",
  "622310 - SPECIALTY (EXCEPT PSYCHIATRIC AND SUBSTANCE ABUSE) HOSPITALS",
  "311422 - SPECIALTY CANNING",
  "333612 - SPEED CHANGER, INDUSTRIAL HIGH-SPEED DRIVE, AND GEAR MANUFACTURING",
  "311942 - SPICE AND EXTRACT MANUFACTURING",
  "339920 - SPORTING AND ATHLETIC GOODS MANUFACTURING",
  "423910 - SPORTING AND RECREATIONAL GOODS AND SUPPLIES MERCHANT WHOLESALERS",
  "459110 - SPORTING GOODS RETAILERS",
  "611620 - SPORTS AND RECREATION INSTRUCTION",
  "711211 - SPORTS TEAMS AND CLUBS",
  "332613 - SPRING MANUFACTURING",
  "424120 - STATIONERY AND OFFICE SUPPLIES MERCHANT WHOLESALERS",
  "322230 - STATIONERY PRODUCT MANUFACTURING",
  "221330 - STEAM AND AIR-CONDITIONING SUPPLY",
  "331513 - STEEL FOUNDRIES (EXCEPT INVESTMENT)",
  "331512 - STEEL INVESTMENT FOUNDRIES",
  "331222 - STEEL WIRE DRAWING",
  "111333 - STRAWBERRY FARMING",
  "238120 - STRUCTURAL STEEL AND PRECAST CONCRETE CONTRACTORS",
  "111991 - SUGAR BEET FARMING",
  "111930 - SUGARCANE FARMING",
  "445110 - SUPERMARKETS AND OTHER GROCERY RETAILERS (EXCEPT CONVENIENCE RETAILERS)",
  "115210 - SUPPORT ACTIVITIES FOR ANIMAL PRODUCTION",
  "213113 - SUPPORT ACTIVITIES FOR COAL MINING",
  "115310 - SUPPORT ACTIVITIES FOR FORESTRY",
  "213114 - SUPPORT ACTIVITIES FOR METAL MINING",
  "213115 - SUPPORT ACTIVITIES FOR NONMETALLIC MINERALS (EXCEPT FUELS) MINING",
  "213112 - SUPPORT ACTIVITIES FOR OIL AND GAS OPERATIONS",
  "323120 - SUPPORT ACTIVITIES FOR PRINTING",
  "488210 - SUPPORT ACTIVITIES FOR RAIL TRANSPORTATION",
  "325613 - SURFACE ACTIVE AGENT MANUFACTURING",
  "212114 - SURFACE COAL MINING",
  "339112 - SURGICAL AND MEDICAL INSTRUMENT MANUFACTURING",
  "339113 - SURGICAL APPLIANCE AND SUPPLIES MANUFACTURING",
  "541370 - SURVEYING AND MAPPING (EXCEPT GEOPHYSICAL) SERVICES",
  "335313 - SWITCHGEAR AND SWITCHBOARD APPARATUS MANUFACTURING",
  "325130 - SYNTHETIC DYE AND PIGMENT MANUFACTURING",
  "325212 - SYNTHETIC RUBBER MANUFACTURING",
  "541213 - TAX PREPARATION SERVICES",
  "485310 - TAXI AND RIDESHARING SERVICES",
  "512191 - TELE PRODUCTION AND OTHER POST PRODUCTION SERVICES",
  "517121 - TELECOMMUNICATIONS RESELLERS",
  "561422 - TELEMARKETING BUREAUS AND OTHER CONTACT CENTERS",
  "561421 - TELEPHONE ANSWERING SERVICES",
  "334210 - TELEPHONE APPARATUS MANUFACTURING",
  "516120 - TELEVISION BROADCASTING STATIONS",
  "561320 - TEMPORARY HELP SERVICES",
  "624221 - TEMPORARY SHELTERS",
  "541380 - TESTING LABORATORIES AND SERVICES",
  "313310 - TEXTILE AND FABRIC FINISHING MILLS",
  "314910 - TEXTILE BAG AND CANVAS MILLS",
  "711110 - THEATER COMPANIES AND DINNER THEATERS",
  "238340 - TILE AND TERRAZZO CONTRACTORS",
  "113110 - TIMBER TRACT OPERATIONS",
  "423130 - TIRE AND TUBE MERCHANT WHOLESALERS",
  "441340 - TIRE DEALERS",
  "326211 - TIRE MANUFACTURING (EXCEPT RETREADING)",
  "326212 - TIRE RETREADING",
  "541191 - TITLE ABSTRACT AND SETTLEMENT OFFICES",
  "111910 - TOBACCO FARMING",
  "312230 - TOBACCO MANUFACTURING",
  "424940 - TOBACCO PRODUCT AND ELECTRONIC CIGARETTE MERCHANT WHOLESALERS",
  "459991 - TOBACCO, ELECTRONIC CIGARETTE, AND OTHER SMOKING SUPPLIES RETAILERS",
  "325620 - TOILET PREPARATION MANUFACTURING",
  "311830 - TORTILLA MANUFACTURING",
  "334514 - TOTALIZING FLUID METER AND COUNTING DEVICE MANUFACTURING",
  "561520 - TOUR OPERATORS",
  "423920 - TOY AND HOBBY GOODS AND SUPPLIES MERCHANT WHOLESALERS",
  "541930 - TRANSLATION AND INTERPRETATION SERVICES",
  "423860 - TRANSPORTATION EQUIPMENT AND SUPPLIES (EXCEPT MOTOR VEHICLE) MERCHANT WHOLESALERS",
  "561510 - TRAVEL AGENCIES",
  "336214 - TRAVEL TRAILER AND CAMPER MANUFACTURING",
  "111335 - TREE NUT FARMING",
  "336212 - TRUCK TRAILER MANUFACTURING",
  "532120 - TRUCK, UTILITY TRAILER, AND RV (RECREATIONAL VEHICLE) RENTAL AND LEASING",
  "523991 - TRUST, FIDUCIARY, AND CUSTODY ACTIVITIES",
  "525920 - TRUSTS, ESTATES, AND AGENCY ACCOUNTS",
  "333611 - TURBINE AND TURBINE GENERATOR SET UNITS MANUFACTURING",
  "112330 - TURKEY PRODUCTION",
  "212115 - UNDERGROUND COAL MINING",
  "326113 - UNLAMINATED PLASTICS FILM AND SHEET (EXCEPT PACKAGING) MANUFACTURING",
  "326121 - UNLAMINATED PLASTICS PROFILE SHAPE MANUFACTURING",
  "337121 - UPHOLSTERED HOUSEHOLD FURNITURE MANUFACTURING",
  "326150 - URETHANE AND OTHER FOAM PRODUCT (EXCEPT POLYSTYRENE) MANUFACTURING",
  "441120 - USED CAR DEALERS",
  "484210 - USED HOUSEHOLD AND OFFICE GOODS MOVING",
  "459510 - USED MERCHANDISE RETAILERS",
  "445132 - VENDING MACHINE OPERATORS",
  "541940 - VETERINARY SERVICES",
  "532282 - VIDEO TAPE AND DISC RENTAL",
  "624310 - VOCATIONAL REHABILITATION SERVICES",
  "813212 - VOLUNTARY HEALTH ORGANIZATIONS",
  "455211 - WAREHOUSE CLUBS AND SUPERCENTERS",
  "423730 - WARM AIR HEATING AND AIR-CONDITIONING EQUIPMENT AND SUPPLIES MERCHANT WHOLESALERS",
  "237110 - WATER AND SEWER LINE AND RELATED STRUCTURES CONSTRUCTION",
  "221310 - WATER SUPPLY AND IRRIGATION SYSTEMS",
  "519290 - WEB SEARCH PORTALS AND ALL OTHER INFORMATION SERVICES",
  "333992 - WELDING AND SOLDERING EQUIPMENT MANUFACTURING",
  "311221 - WET CORN MILLING AND STARCH MANUFACTURING",
  "111140 - WHEAT FARMING",
  "425120 - WHOLESALE TRADE AGENTS AND BROKERS",
  "221115 - WIND ELECTRIC POWER GENERATION",
  "449122 - WINDOW TREATMENT RETAILERS",
  "424820 - WINE AND DISTILLED ALCOHOLIC BEVERAGE MERCHANT WHOLESALERS",
  "312130 - WINERIES",
  "517111 - WIRED TELECOMMUNICATIONS CARRIERS",
  "517112 - WIRELESS TELECOMMUNICATIONS CARRIERS (EXCEPT SATELLITE)",
  "321920 - WOOD CONTAINER AND PALLET MANUFACTURING",
  "337110 - WOOD KITCHEN CABINET AND COUNTERTOP MANUFACTURING",
  "337211 - WOOD OFFICE FURNITURE MANUFACTURING",
  "321114 - WOOD PRESERVATION",
  "321911 - WOOD WINDOW AND DOOR MANUFACTURING",
  "712130 - ZOOS AND BOTANICAL GARDENS",
] as const;

const STATES = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "District of Columbia",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
] as const;

type AppetiteCarrier = {
  name: string;
  logo: string;
  badge?: "E&S";
};

const APPETITE_CARRIERS: AppetiteCarrier[] = [
  { name: "Accident Fund", logo: "/images/appetite/accidentFund_logo.jpg" },
  { name: "AmTrust", logo: "/images/appetite/amtrust_logo.png" },
  { name: "biBerk", logo: "/images/appetite/biberk_logo.png" },
  { name: "Chubb", logo: "/images/appetite/chubb_padding_logo.png" },
  { name: "CNA", logo: "/images/appetite/cna_logo.png" },
  { name: "Coalition", logo: "/images/appetite/coalition_logo.png" },
  {
    name: "Coalition",
    logo: "/images/appetite/coalition_logo.png",
    badge: "E&S",
  },
  { name: "Coterie", logo: "/images/appetite/coterie_logo.jpg" },
  { name: "Cowbell", logo: "/images/appetite/cowbell_logo.png" },
  { name: "Employers", logo: "/images/appetite/employers_logo.png" },
  { name: "First Insurance", logo: "/images/appetite/first_insurance_logo.png" },
  { name: "GUARD", logo: "/images/appetite/guard_logo.png" },
  { name: "Hiscox", logo: "/images/appetite/hiscox_logo.png" },
  { name: "Liberty Mutual", logo: "/images/appetite/lm_logo.png" },
  { name: "Markel", logo: "/images/appetite/markel_logo.png" },
  { name: "Merchants", logo: "/images/appetite/merchants_logo.png" },
  { name: "NBS", logo: "/images/appetite/nbs_logo.png" },
  {
    name: "Penn America Surplus",
    logo: "/images/appetite/penn_america_surplus_logo.png",
    badge: "E&S",
  },
  { name: "Pie Insurance", logo: "/images/appetite/pie_insurance_logo.png" },
  {
    name: "Republic Indemnity",
    logo: "/images/appetite/republic_indemnity_logo.png",
  },
  { name: "Travelers", logo: "/images/appetite/travelers_logo.png" },
  {
    name: "USLI",
    logo: "/images/appetite/usli_logo.png",
    badge: "E&S",
  },
  {
    name: "Westchester",
    logo: "/images/appetite/westchester_logo.jpg",
    badge: "E&S",
  },
];

function CarrierLogoCard({
  carrier,
}: {
  carrier: AppetiteCarrier;
}) {
  const cardRef = useRef<HTMLElement>(null);
  const glowRef = useRef<HTMLDivElement>(null);

  const handleMouseMove = (event: MouseEvent<HTMLElement>) => {
    const card = cardRef.current;
    const glow = glowRef.current;
    if (!card || !glow) return;

    const rect = card.getBoundingClientRect();
    const x = event.clientX - rect.left;
    const y = event.clientY - rect.top;
    const glowSize = Math.max(rect.width, rect.height) * 1.75;

    glow.style.background = `radial-gradient(${glowSize}px circle at ${x}px ${y}px, rgba(1, 48, 190, 1) 0%, rgba(45, 62, 157, 0.65) 14%, rgba(45, 62, 157, 0.22) 32%, transparent 58%)`;
    glow.style.opacity = "1";
  };

  const handleMouseLeave = () => {
    if (glowRef.current) {
      glowRef.current.style.opacity = "0";
    }
  };

  return (
    <article
      ref={cardRef}
      data-appetite-animate
      onMouseMove={handleMouseMove}
      onMouseLeave={handleMouseLeave}
      className="group relative overflow-hidden rounded-[20px] bg-[#ECECEC] p-[1.5px] transition-transform duration-500 ease-[cubic-bezier(0.22,1,0.36,1)] will-change-transform hover:-translate-y-1 hover:scale-[1.015]"
    >
      <div
        ref={glowRef}
        className="pointer-events-none absolute inset-0 opacity-0 transition-opacity duration-300"
      aria-hidden
    />
      <div className="relative z-10 flex h-22 items-center justify-center overflow-hidden rounded-[19px] bg-white px-4 py-4 transition-shadow duration-500 group-hover:shadow-[0_18px_40px_-28px_rgba(10,20,59,0.45)] sm:h-24 md:h-28">
        {carrier.badge ? (
          <span className="absolute left-2 top-2 rounded bg-[#F4A261] px-1.5 py-0.5 font-mono text-[0.5625rem] font-semibold uppercase leading-none tracking-wide text-white">
            {carrier.badge}
    </span>
        ) : null}
        <Image
          src={carrier.logo}
          alt={`${carrier.name} logo`}
          width={110}
          height={36}
          className="max-h-6 w-auto max-w-[75%] object-contain transition-transform duration-500 ease-[cubic-bezier(0.22,1,0.36,1)] group-hover:scale-105 sm:max-h-7 md:max-h-8"
        />
      </div>
    </article>
  );
}

function formatDropdownLabel(option: string) {
  // Keep mixed-case labels (policy types, states) as-is.
  if (/[a-z]/.test(option)) return option;

  // Title-case all-caps labels (e.g. NAICS industry names).
  return option
    .toLowerCase()
    .replace(/(^|[\s\-/(])([a-z])/g, (_, prefix: string, char: string) => prefix + char.toUpperCase());
}

function FormSelect({
  id,
  label,
  value,
  options,
  onChange,
}: {
  id: string;
  label: string;
  value: string;
  options: readonly string[];
  onChange: (value: string) => void;
}) {
  const [open, setOpen] = useState(false);
  const rootRef = useRef<HTMLDivElement>(null);
  const listId = `${id}-listbox`;
  const selected = options.includes(value) ? value : options[0];
  const selectedLabel = formatDropdownLabel(selected);

  useEffect(() => {
    if (!open) return;

    const onPointerDown = (event: globalThis.MouseEvent) => {
      if (!rootRef.current?.contains(event.target as Node)) {
        setOpen(false);
      }
    };
    const onKeyDown = (event: globalThis.KeyboardEvent) => {
      if (event.key === "Escape") setOpen(false);
    };

    document.addEventListener("mousedown", onPointerDown);
    document.addEventListener("keydown", onKeyDown);
    return () => {
      document.removeEventListener("mousedown", onPointerDown);
      document.removeEventListener("keydown", onKeyDown);
    };
  }, [open]);

  return (
    <div ref={rootRef} className="relative block min-w-0 flex-1">
      <span
        id={`${id}-label`}
        className="mb-2 block font-mono text-sm font-medium uppercase text-[#2A297C]"
      >
        {label}
      </span>
      <button
          id={id}
        type="button"
        aria-haspopup="listbox"
        aria-expanded={open}
        aria-controls={listId}
        aria-labelledby={`${id}-label`}
        onClick={() => setOpen((prev) => !prev)}
        className={`box-border flex h-10 min-h-10 max-h-10 w-full items-center justify-between rounded-lg border bg-white px-4 text-left font-heading text-sm font-medium leading-none outline-none transition-colors ${
          open
            ? "border-[#5B35E0] text-[#1A1A1A] ring-1 ring-[#5B35E0]/20"
            : "border-[#E4E7EC] text-[#1A1A1A] hover:border-[#5B35E0]/40"
        }`}
      >
        <span className="truncate text-[#1A1A1A]">{selectedLabel}</span>
        <ChevronDown
          className={`ml-3 size-4 shrink-0 text-[#9AA8BC] transition-transform duration-200 ${
            open ? "rotate-180" : ""
          }`}
          aria-hidden
        />
      </button>

      {open ? (
        <ul
          id={listId}
          role="listbox"
          aria-labelledby={`${id}-label`}
          data-lenis-prevent
          className="absolute left-0 right-0 top-[calc(100%+6px)] z-30 max-h-64 overflow-y-auto rounded-xl border border-[#E8ECF0] bg-white py-1 shadow-[0_12px_32px_rgba(10,20,59,0.1)]"
        >
          {options.map((option, index) => {
            const isSelected = option === value;
            return (
              <li key={option} role="presentation">
                <button
                  type="button"
                  role="option"
                  aria-selected={isSelected}
                  onClick={() => {
                    onChange(option);
                    setOpen(false);
                  }}
                  className={`flex w-full items-center px-4 py-3.5 text-left font-heading text-xs font-medium transition-colors md:text-sm ${
                    index > 0 ? "border-t border-[#EEF1F5]" : ""
                  } ${
                    isSelected
                      ? "bg-[#F5F3FF] text-[#2A297C]"
                      : "text-[#111110] hover:bg-[#F7F8FA]"
                  }`}
                >
                  {formatDropdownLabel(option)}
                </button>
              </li>
            );
          })}
        </ul>
      ) : null}
      </div>
  );
}

const Appetite = () => {
  const [policyType, setPolicyType] = useState<string>(POLICY_TYPES[0]);
  const [industry, setIndustry] = useState<string>(INDUSTRIES[1]);
  const [state, setState] = useState<string>(STATES[0]);
  const sectionRef = useRef<HTMLElement>(null);
  const headerRef = useRef<HTMLDivElement>(null);
  const headingRef = useRef<HTMLHeadingElement>(null);
  const descRef = useRef<HTMLParagraphElement>(null);
  const resultsRef = useRef<HTMLDivElement>(null);

  useSectionHeaderReveal({
    scopeRef: sectionRef,
    headerRef,
    headingRef,
    descRef,
    theme: "dark",
  });

  useGSAP(
    () => {
      if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;

      const container = resultsRef.current;
      if (!container) return;

      const items = gsap.utils.toArray<HTMLElement>("[data-appetite-animate]");
      if (!items.length) return;

      const animateIn = () => {
        gsap.killTweensOf(items);
        gsap.set(items, { opacity: 0, y: 20 });
        gsap.to(items, {
          opacity: 1,
          y: 0,
          duration: 0.55,
          ease: "power3.out",
          stagger: 0.05,
          overwrite: true,
        });
      };

      const rect = container.getBoundingClientRect();
      const inView = rect.top < window.innerHeight * 0.88;

      let st: ScrollTrigger | null = null;

      if (inView) {
        animateIn();
      } else {
        gsap.set(items, { opacity: 0, y: 20 });
        st = ScrollTrigger.create({
          trigger: container,
          start: "top 88%",
          once: true,
          onEnter: animateIn,
        });
      }

      const lenis = window.lenis;
      const onLenisScroll = () => ScrollTrigger.update();
      lenis?.on("scroll", onLenisScroll);

      return () => {
        st?.kill();
        lenis?.off("scroll", onLenisScroll);
        gsap.killTweensOf(items);
      };
    },
    { scope: resultsRef },
  );

  return (
    <section id="appetite" ref={sectionRef} className="relative bg-[#121C49] text-white">
      <div
        className="pointer-events-none absolute inset-0 hidden md:block"
        style={{
          background:
            "radial-gradient(ellipse 95% 85% at 50% 58%, rgba(49, 78, 155, 0.55) 0%, rgba(18, 28, 73, 0.92) 52%, #121C49 100%)",
        }}
        aria-hidden
      />

      <Container borderColor="#FFFFFF33" className="relative z-10 border-t border-[#FFFFFF1A]">
        <div className="py-16 md:py-20 lg:py-24">
          <div
            ref={headerRef}
            className="relative z-10 mx-auto max-w-3xl text-center"
          >
            <h2
              ref={headingRef}
              className="mx-auto max-w-md text-2xl font-heading font-medium leading-[1.15] tracking-tight text-[#BCC5D6] sm:text-3xl sm:leading-[1.12] md:text-4xl lg:text-[1.625rem] lg:leading-[1.12]"
            >
              <span data-split>CoverForce </span>
              <span data-split className="text-[#413CC0]">
                Appetite Engine
              </span>
            </h2>

            <p
              ref={descRef}
              className="mx-auto mt-5 max-w-xl font-sans font-regular text-sm leading-[1.4] text-white/80 md:text-[1.125rem]"
            >
              Check carrier appetite for any class code - powered by 140K+
              proprietary carrier interactions.
            </p>
          </div>

          <div className="relative mx-auto mt-12 max-w-6xl overflow-visible md:mt-14 lg:mt-16">
            <SectionRadialGlow className="absolute left-1/2 top-[58%] z-0 hidden w-[145%] max-w-[76rem] -translate-x-1/2 -translate-y-[42%] blur-[4.5rem] opacity-90 md:block" />

            <div className="relative z-10 rounded-2xl bg-white p-5 text-[#0a143b] shadow-[0_24px_80px_rgba(0,0,0,0.28)] md:p-8 lg:p-10">
              <form className="space-y-6" onSubmit={(event) => event.preventDefault()}>
                <div className="relative z-20 grid items-end gap-4 md:grid-cols-4">
                  <FormSelect
                    id="appetite-policy-type"
                    label="Policy Type"
                    value={policyType}
                    options={POLICY_TYPES}
                    onChange={setPolicyType}
                  />
                  <FormSelect
                    id="appetite-industry"
                    label="Industry"
                    value={industry}
                    options={INDUSTRIES}
                    onChange={setIndustry}
                  />
                  <FormSelect
                    id="appetite-state"
                    label="State"
                    value={state}
                    options={STATES}
                    onChange={setState}
                    />
                    <Button
                      type="submit"
                      variant="primary"
                    className="flex h-10 min-h-10 max-h-10 w-full items-center justify-center text-center"
                    >
                      Check Appetite
                    </Button>
                </div>

              </form>

              <div
                ref={resultsRef}
                className="mt-8 overflow-visible border-t border-[#ECEEF2] pt-6 md:mt-10 md:pt-8"
              >
                <p
                  data-appetite-animate
                  className="mb-5 font-heading text-base font-medium text-[#1A1A1A] md:text-lg"
                >
                  {APPETITE_CARRIERS.length} Carriers available
                </p>

                <div className="grid grid-cols-2 gap-3 px-1 py-1 sm:grid-cols-3 md:grid-cols-4 md:gap-4">
                  {APPETITE_CARRIERS.map((carrier, index) => (
                    <CarrierLogoCard
                      key={`${carrier.name}-${carrier.badge ?? "admitted"}-${index}`}
                      carrier={carrier}
                          />
                        ))}
                      </div>
              </div>
            </div>
          </div>
        </div>
      </Container>
    </section>
  );
};

export default Appetite;
