import Link from "next/link";
import type { LegalPageProps } from "@/components/legal/LegalPage";

const linkClass = "text-[#3D3D3D] underline underline-offset-2";

export const iaAgreementContent: LegalPageProps = {
  eyebrow: "Legal",
  title: "CoverForce Independent Agency Customer Agreement",
  lastUpdated: "September 20, 2026",
  sections: [
    {
      title: "Definitions",
      paragraphs: [
        <>
          <span className="font-medium text-[#444444]">Services:</span> means the products,
          deliverables, or other offerings provided by CoverForce, Inc. as described on the Pricing
          Terms for the Plan that Customer selects. The scope and nature of the Services shall be as
          described there and may include updates, support, or other features as further detailed
          therein.
        </>,
        <>
          <span className="font-medium text-[#444444]">Plan:</span> means the subscription plan
          Customer selects when it signs up for the Services, as described on the Pricing Terms.
        </>,
        <>
          <span className="font-medium text-[#444444]">Pricing Terms:</span> means the pricing and
          plan terms for the Plan that CoverForce presents to Customer at registration and that
          Customer accepts together with these Terms, setting out the Subscription Fee, the Included
          Submissions, the Overage Rate, any Introductory Credit, the volume threshold and the other
          commercial terms of the Plan, in each case as varied from time to time under Section 6(f).
          CoverForce also publishes general pricing information at{" "}
          <Link href="/pricing" className={linkClass}>
            coverforce.com/pricing
          </Link>
          ; where that published information differs from the Pricing Terms accepted by Customer, the
          Pricing Terms control. The Pricing Terms form part of this Agreement.
        </>,
        <>
          <span className="font-medium text-[#444444]">Privacy Policy:</span> means CoverForce&apos;s
          privacy policy published at{" "}
          <Link href="/privacy-policy" className={linkClass}>
            https://www.coverforce.com/privacy-policy
          </Link>
          , as updated from time to time. The Privacy Policy is a notice describing CoverForce&apos;s
          data practices; it is not incorporated into this Agreement.
        </>,
        <>
          <span className="font-medium text-[#444444]">Authorized Users:</span> means Customer&apos;s
          employees, contractors and, where Customer is a licensed insurance intermediary, its
          insurance agents and producers, in each case authorized by Customer to access and use the
          Services on Customer&apos;s behalf. Each Authorized User must be provisioned under
          Customer&apos;s tenant and may not share credentials. Persons who submit information about
          their own risk through Customer&apos;s consumer-facing interface are not Authorized Users;
          Customer is responsible for their activity.
        </>,
        <>
          <span className="font-medium text-[#444444]">Customer Credentials:</span> means the producer
          codes, agency codes, appointment identifiers, portal credentials and other access credentials
          issued or authorized by a carrier, network, aggregator or wholesaler that Customer provides
          to CoverForce for use through the Services.
        </>,
        <>
          <span className="font-medium text-[#444444]">Submission:</span> means the transmission
          through the Services of one quote application to one distinct carrier or market (a
          &quot;Market&quot;) by or on behalf of Customer or its Authorized Users. Each
          application-Market pair is counted once per calendar month regardless of the number or
          outcome of responses (quotes, referrals or declinations), whether or not the calendar month
          coincides with a Billing Period. Re-rating or amending an application already transmitted to
          a Market is not a new Submission. Appetite checks, application creation and bind or issuance
          requests are not Submissions. CoverForce&apos;s records of Submissions are conclusive absent
          manifest error and will be made available to Customer through the Services.
        </>,
        <>
          <span className="font-medium text-[#444444]">Billing Period:</span> means each period of the
          length stated on the Pricing Terms (monthly unless the Pricing Terms state otherwise)
          beginning on the date Customer&apos;s paid subscription starts and on the corresponding day
          of each subsequent period. At the start of each Billing Period the Included Submissions
          reset and cumulative Submission counts return to zero; unused Submissions expire. Where a
          Billing Period is longer than one month, the Included Submissions for that Billing Period
          are available in full from its start and may be used in any calendar month within it. A
          &quot;calendar month&quot; is a month of the Gregorian calendar, whether or not it coincides
          with a Billing Period.
        </>,
        <>
          <span className="font-medium text-[#444444]">Introductory Credit:</span> means a credit
          against the Subscription Fee offered on the Pricing Terms from time to time, of the amount
          and for the number of Billing Periods, or the period, stated there. Where the Pricing Terms
          state a period that is not a whole number of Billing Periods, the credit applies to each
          Billing Period that begins within that period.
        </>,
        <>
          <span className="font-medium text-[#444444]">Carrier Data:</span> means quotes, rates,
          appetite, underwriting responses and other information a carrier returns through the
          Services, and any data derived from them. Carrier Data is not Customer Data.
        </>,
        <>
          <span className="font-medium text-[#444444]">CoverForce Connectors:</span> means connectors,
          plug-ins and integrations that CoverForce itself provides or designates in the Documentation
          for use with the Services, including connectors that allow a third-party artificial
          intelligence assistant to create applications and submit information to the Services.
        </>,
      ],
    },
    {
      title: "Acceptance",
      paragraphs: [
        'PLEASE READ THESE TERMS ("TERMS") CAREFULLY BEFORE USING THE SERVICES OFFERED BY COVERFORCE, INC. ("COVERFORCE"). BY CLICKING "I AGREE" AT REGISTRATION, YOU ("CUSTOMER") ACCEPT THIS CUSTOMER AGREEMENT, CONSISTING OF THESE TERMS AND THE PRICING PAGE (TOGETHER, THE "AGREEMENT"), TO THE EXCLUSION OF ALL OTHER TERMS, AND ACKNOWLEDGE THE PRIVACY POLICY. THIS AGREEMENT GOVERNS CUSTOMER\'S USE OF THE SERVICES AND SUPERSEDES THE WEBSITE TERMS OF SERVICE PUBLISHED AT COVERFORCE.COM TO THE EXTENT OF ANY CONFLICT. IF YOU ARE ACCEPTING ON BEHALF OF AN AGENCY OR OTHER ENTITY, YOU REPRESENT THAT YOU HAVE AUTHORITY TO BIND THAT ENTITY, AND "CUSTOMER" MEANS THAT ENTITY. IF THE TERMS OF THIS AGREEMENT ARE CONSIDERED AN OFFER, ACCEPTANCE IS EXPRESSLY LIMITED TO SUCH TERMS. SECTION 17 CONTAINS A BINDING ARBITRATION PROVISION AND A CLASS ACTION WAIVER THAT AFFECT YOUR LEGAL RIGHTS.',
      ],
    },
    {
      title: "1. Your Plan; Access to the Service",
      paragraphs: [
        'The Plan that Customer selects at sign-up, and the Pricing Terms, are incorporated into and form part of the Agreement. Subject to Customer\'s compliance with the terms and conditions of this Agreement (including any limitations and restrictions set forth on the Pricing Terms) CoverForce grants Customer and each Authorized User the right to access and use the services included in the Plan (collectively, the "Service," or "Services") during the Term for the internal business purposes of Customer, only as provided herein and only in accordance with CoverForce\'s applicable official user documentation (the "Documentation"). The Plan does not include access to CoverForce\'s APIs or the issue of API keys; access to the Services under the Plan is through the CoverForce agent portal and CoverForce Connectors only. Each Authorized User must have its own unique account on the Services and Authorized Users may not share their account credentials with one another or any third party. Customer will be responsible for all of the acts and omissions of its Authorized Users in connection with this Agreement and for all use of Authorized Users\' accounts. If Customer becomes aware of fraud or other improper actions by an Authorized User, it is Customer\'s responsibility to revoke the credentials of such Authorized User and otherwise act to prevent further unauthorized access and/or use of the Customer\'s information by such Authorized User through the Services.',
      ],
    },
    {
      title: "2. Eligibility; Account Information",
      paragraphs: [
        "(a) Eligibility. Customer represents on acceptance, and covenants throughout the Term, that: (i) Customer is an insurance agency or individual producer licensed and in good standing in every state in which it transacts insurance through the Services; (ii) Customer is appointed by, or otherwise authorized to submit business to, each carrier to which it submits through the Services; (iii) Customer maintains errors and omissions (professional liability) insurance covering its insurance agency operations; (iv) Customer is organized and operates in the United States; and (v) the individual accepting this Agreement is at least eighteen years of age and authorized to bind Customer.",
        "(b) Notice; evidence. Customer shall notify CoverForce within five (5) business days of any suspension, revocation, non-renewal or disciplinary action affecting any license or appointment used with the Services, or any lapse of the insurance described in paragraph (a)(iii). On request, Customer shall provide license numbers (including National Producer Number), appointment confirmations and evidence of insurance.",
        "(c) Account information. Customer represents that all registration and account information is truthful, accurate and complete, and shall keep it current. CoverForce may suspend an account whose information is inaccurate or cannot be verified.",
        "(d) Breach of this Section is a material breach permitting immediate termination under Section 12.",
      ],
    },
    {
      title: "3. Support",
      paragraphs: [
        "CoverForce may provide support for the Services at its discretion through the channels described in the Documentation. The Services may be unavailable from time to time. CoverForce has no availability, uptime, support or response-time obligation under this Plan.",
      ],
    },
    {
      title: "4. Service Updates",
      paragraphs: [
        'From time to time, CoverForce may provide upgrades, patches, enhancements, or fixes for the Services to its customers generally without additional charge ("Updates"), and such Updates will become part of the Services and subject to this Agreement; provided that CoverForce shall have no obligation under this Agreement or otherwise to provide any such Updates. Customer understands that CoverForce may cease supporting old versions or releases of the Services at any time in its sole discretion. Carrier, product and line of business availability is not guaranteed; CoverForce may add, suspend or remove any carrier, product or line of business without liability or refund. No carrier, product or line of business is promised under the Plan, and none is a condition of it.',
      ],
    },
    {
      title: "5. Ownership; Feedback",
      paragraphs: [
        'As between the parties, CoverForce retains all right, title, and interest in and to the Services, and all software, products, works, and other intellectual property and moral rights related thereto or created, used, or provided by CoverForce for the purposes of this Agreement, including any copies and derivative works of the foregoing. Any software which is distributed or otherwise provided to Customer hereunder shall be deemed a part of the "Services" and subject to all of the terms and conditions of this Agreement. No rights or licenses are granted except as expressly and unambiguously set forth in this Agreement. Customer may from time to time provide suggestions, comments or other feedback to CoverForce with respect to the Service ("Feedback"). Feedback, even if designated as confidential by Customer, shall not create any confidentiality obligation for CoverForce notwithstanding anything else. Customer shall, and hereby does, grant to CoverForce a nonexclusive, worldwide, perpetual, irrevocable, transferable, sublicensable, royalty-free, fully paid up license to use and exploit the Feedback for any purpose. Nothing in this Agreement will impair CoverForce\'s right to develop, acquire, license, market, promote or distribute products, software or technologies that perform the same or similar functions as, or otherwise compete with any products, software or technologies that Customer may develop, produce, market, or distribute.',
      ],
    },
    {
      title: "6. Fees; Payment",
      paragraphs: [
        '(a) Fees. Customer shall pay CoverForce the fees set forth on the Pricing Terms ("Fees"). The Pricing Terms state the subscription fee for the Plan for each Billing Period (the "Subscription Fee"), the number of Submissions included in the Subscription Fee in each Billing Period (the "Included Submissions"), the per-Submission rate applicable to Submissions in excess of the Included Submissions (the "Overage Rate") and any Introductory Credit, if any. Where these Terms and the Pricing Terms conflict as to a commercial term, the Pricing Terms control.',
        "(b) Introductory Credit. Where the Pricing Terms offer an Introductory Credit, CoverForce applies it automatically against the Subscription Fee for each of the first Billing Periods stated there, or where the Pricing Terms state a period, for each Billing Period beginning within that period, in each case starting with the Billing Period in which Customer's subscription starts. The Introductory Credit applies to the Subscription Fee only. It does not apply to Overage Charges, taxes or any one-time fee, which remain payable when due. The Introductory Credit is applied in the Billing Period to which it relates, does not carry over, has no cash value, is not refundable or exchangeable, and may not be applied to any other CoverForce plan or program. Customer must provide a valid payment method before the subscription starts. An Introductory Credit is a promotional offer and not a term of the Plan: whether one is offered, its amount and the number of Billing Periods it covers are stated on the Pricing Terms from time to time, CoverForce may offer, change or withdraw it prospectively, and CoverForce may limit it to one per agency and withhold it where it reasonably suspects abuse or circumvention. Customer's subscription is a paid subscription from the date it starts, whether or not an Introductory Credit applies, and all other provisions of this Agreement apply in full during any credited Billing Period.",
        "(c) Payment in advance. The Subscription Fee is payable in advance for each Billing Period. Customer authorizes CoverForce and its payment processors to charge Customer's payment method on file for the Subscription Fee on the first day of each Billing Period and for all other amounts due under this Agreement as they become due, and to store and update that payment method. Customer shall maintain a valid payment method on file at all times during the Term.",
        '(d) Overage Charges. Submissions in excess of the Included Submissions in a Billing Period are billed at the Overage Rate ("Overage Charges"), calculated at the end of the Billing Period in which they accrue and charged in arrears together with the next Subscription Fee; Overage Charges for the final Billing Period of the Term are charged within thirty (30) days after it ends. Unused Submissions do not roll over and have no cash value.',
        "(e) Volume threshold. The Pricing Terms state a monthly Submission volume above which the Plan is no longer offered, measured in each calendar month regardless of the length of the Billing Period. If Customer exceeds that volume in any calendar month, CoverForce may require Customer to move to a different plan on thirty (30) days' notice, and if Customer does not do so within that period may cancel the subscription at the end of it. CoverForce is not obligated to interrupt or block Customer's use of the Services on reaching that volume, and any failure to do so is not a waiver of this paragraph.",
        "(f) Price changes. CoverForce may change the Fees on thirty (30) days' written notice to Customer. A change takes effect at the start of the first Billing Period beginning after that notice period ends. Customer's sole remedy if it does not agree to a change is to cancel under Section 12 before the change takes effect.",
        "(g) Failed payment. If a charge to Customer's payment method fails, CoverForce may re-attempt the charge. If any Fee remains unpaid ten (10) days after it became due, CoverForce may suspend access to the Services until payment is received.",
        "(h) Billing disputes. Customer must notify CoverForce in writing of any disputed charge within thirty (30) days of the charge date, stating the basis for the dispute; charges not disputed within that period are deemed accepted. Customer shall not initiate a chargeback or payment reversal with its payment provider for any charge without first disputing it under this paragraph and allowing CoverForce fifteen (15) days to respond. Initiating a chargeback in breach of this paragraph is a material breach and CoverForce may suspend the Services until the amount is paid.",
        "(i) Plan eligibility; no combination. The Plan is offered on the basis that Customer is not concurrently a customer on, and does not concurrently receive the benefit of, any other CoverForce plan, program or pricing, including the CoverForce Startup Program, any enterprise plan and any discounted, promotional, partner or individually negotiated pricing. Subscribing to the Plan makes Customer ineligible for any such plan, program or pricing for so long as the subscription continues, and Customer may not combine the Plan with, or apply to it any discount, credit, promotional rate or other benefit offered under, any of them. Any discount, credit or promotional rate applicable to the Plan itself is as stated on the Pricing Terms. Customer may not move to the Plan from any other CoverForce plan or program. Customer shall maintain a single account on the Plan and shall not divide or route its business across more than one account, or across affiliates or related agencies, so as to remain within the Included Submissions or the volume threshold in Section 6(e). If Customer is or becomes a party to another CoverForce plan or program, CoverForce may on thirty (30) days' notice cancel the subscription or move Customer to that other plan.",
        "(j) Implementation and other one-time fees. No implementation, onboarding, configuration, training or other one-time fee applies to the Plan unless the Pricing Terms state one. Where the Pricing Terms state such a fee, it is payable in advance of the Services to which it relates, is non-refundable, is not creditable against any other Fee, and is additional to the Subscription Fee and any Overage Charges.",
        "Past-due invoices are subject to interest on any outstanding balance of the lesser of 1.5% per month or the maximum amount permitted by law. Customer shall be responsible for all taxes associated with the Service (excluding taxes based on CoverForce's net income). All Fees paid are non-refundable, are not prorated on cancellation or suspension, and are not subject to set-off.",
      ],
    },
    {
      title: "7. Restrictions",
      paragraphs: [
        "Except as expressly set forth in this Agreement, Customer and any Authorized Users shall not (and shall not permit any third party to), directly or indirectly: (i) reverse engineer, decompile, disassemble, or otherwise attempt to discover the source code, object code, or underlying structure, ideas, or algorithms of the Service (except to the extent applicable laws specifically prohibit such restriction); (ii) modify, translate, or create derivative works based on the Service; (iii) copy, rent, lease, distribute, pledge, assign, or otherwise transfer or encumber rights to the Service; (iv) use the Service for the benefit of a third party, including to place, quote or bind business on behalf of any agency other than Customer; (v) remove or otherwise alter any proprietary notices or labels from the Service or any portion thereof; (vi) use the Service or the APIs to replicate CoverForce's carrier connectivity or to build a competing carrier-integration or quoting-connectivity service; (vii) interfere or attempt to interfere with the proper working of the Service or any activities conducted on the Service; or (viii) bypass any measures CoverForce may use to prevent or restrict access to the Service (or other accounts, computer systems or networks connected to the Service).",
        'Customer is responsible for all of Customer\'s activity in connection with the Service, including but not limited to uploading Customer Data onto the Service. Customer and its Authorized Users (i) shall comply with all applicable local, state, national and foreign laws, treaties and regulations in connection with Customer\'s use of the Service (including those related to data privacy, international communications, regulations, licensing requirements, export laws and the transmission of technical or personal data laws) (collectively, "Applicable Laws"), (ii) shall use the Service in compliance with all Applicable Laws and (iii) shall not use the Service in a manner that violates any third party intellectual property, contractual or other proprietary rights.',
      ],
    },
    {
      title: "8. Access and Carrier Requirements",
      paragraphs: [
        "(a) Users. Customer shall provision Authorized Users through the Services, keep the user register current, and record each user's country of access. Without CoverForce's prior written consent, no Authorized User may access the Services from outside the United States, and Customer shall not permit any third-party technology, development or processing vendor (other than through CoverForce Connectors used in accordance with this Agreement) to access the Services or Carrier Data. An Authorized User may submit business to a carrier only if licensed, appointed by that carrier, and using credentials the carrier has issued or authorized.",
        "(b) Removal. CoverForce may suspend or remove any Authorized User or carrier from Customer's account on notice, including at a carrier's request. Customer shall disable any Authorized User within twenty-four (24) hours of CoverForce's instruction. Neither is a breach by CoverForce or reduces Fees.",
        "(c) Carrier Data. Customer shall use Carrier Data solely to quote, bind and service the risk to which it relates; present it accurately and unaltered; treat rates, quotes and appetite as Confidential Information; and shall not, in any form including de-identified or aggregated, aggregate it, use it to train, tune or improve any artificial intelligence or machine learning model, benchmark or replicate any carrier's pricing or appetite, or disclose it to another carrier. Customer may use Carrier Data as an input to automated or AI-assisted tools solely to quote, bind or service the specific risk, provided such data is not retained by or used to train, tune or improve any model. Quotes are indications until the carrier confirms. Customer shall retain Submission records for three (3) years and return or destroy Carrier Data within thirty (30) days of request or termination, except Submission records retained under this paragraph or as required by Applicable Laws, which remain subject to Section 11. This paragraph does not restrict Customer's use of Customer Data.",
        "(d) Marks. Nothing in this Agreement grants Customer any right to use any carrier's name, logo or marks. CoverForce has not obtained and does not give any carrier's consent to such use; any such use is a matter between Customer and the carrier.",
        "(e) Audit. Customer shall permit CoverForce or the relevant carrier to audit compliance with this Section on reasonable notice.",
        "(f) Carrier Requirements. Customer shall comply with carrier access, licensing and data requirements that CoverForce notifies the Customer in writing. A carrier may withdraw its products from Customer or any Authorized User at any time.",
        "(g) Fair use; rate limits. The Services are metered by Submissions. Appetite checks, application creation, re-rating, data retrieval and other calls that are not Submissions are provided for Customer's ordinary business use and are subject to the rate limits and fair-use thresholds. CoverForce may set and change those limits, and may throttle, queue or suspend access that exceeds them or that in CoverForce's reasonable judgment places undue load on the Services or on any carrier's systems.",
        "(h) Customer Credentials. Customer authorizes CoverForce to use Customer Credentials to transmit applications and bind requests to carriers and to retrieve Carrier Data on Customer's behalf through the Services, and to store Customer Credentials for that purpose. Customer represents and warrants that (i) it holds each Customer Credential in its own right or under a network, aggregator or wholesaler arrangement that permits its use through a third-party technology platform, (ii) CoverForce's use of Customer Credentials as permitted by this Agreement will not breach any producer, appointment, network, aggregator or other agreement binding on Customer, and (iii) it has the right to provide Customer Credentials to CoverForce. Customer shall notify CoverForce within twenty-four (24) hours if any Customer Credential is suspended, revoked, reassigned or disputed, and CoverForce may disable any Customer Credential immediately, including at a carrier's or network's request.",
      ],
    },
    {
      title: "9. Artificial Intelligence Features; Connectors",
      paragraphs: [
        '(a) Definitions. "AI Features" means those parts of the Services that use artificial intelligence, machine learning, large language models or similar technologies, including document reading and extraction, email intake, application pre-fill, renewal population, summarization and drafting. "Input" means data that Customer or its Authorized Users provide to the AI Features or submit to the Services through a CoverForce Connector. "Output" means content the AI Features generate in response to an Input. Inputs and Outputs are Customer Data and are subject to Section 10. A third-party artificial intelligence assistant or platform accessed through a CoverForce Connector is not an AI Feature and is not part of the Services; CoverForce is not responsible for anything such an assistant or platform generates.',
        "(b) Decision support only; human review. The AI Features are decision-support tools. They do not solicit, negotiate, sell or bind insurance, and they do not exercise underwriting judgment. Output is generated by probabilistic models, may be inaccurate, incomplete or out of date, and is not tested, verified, endorsed or guaranteed to be accurate, complete or current by CoverForce. Customer shall cause every application, submission, quote comparison, bind request and other communication derived in whole or in part from Output, or prepared in whole or in part with any third-party tool and submitted through the Services, to be reviewed and approved, taking into account information beyond the Output, by a natural person acting for Customer who holds the licenses required for that activity, before it is transmitted to any carrier, applicant or insured. Customer shall not configure, script or otherwise use the Services or any CoverForce Connector to transmit an application or a bind request to any carrier without that review and approval. Output is not legal, underwriting, coverage, suitability or other professional advice and is not a substitute for Customer's professional judgment. Customer assumes all risk and liability arising from its own reliance on Output, from a third party's reliance on Output that Customer provides or makes available, and from any Output that Customer induces a third party to rely upon.",
        "(c) Licensing; authority; attestation. Customer represents that all licensed insurance activity conducted through the Services is performed by or under the supervision of natural persons holding the producer licenses and carrier appointments required by Applicable Laws for that activity. Nothing in this Agreement grants, expands or delegates any binding authority; Customer's binding authority derives solely from its agreements with the applicable carriers, and Customer shall not use the Services, including the AI Features, in excess of it. Customer is solely responsible for the accuracy and completeness of every application submitted through the Services, including content that originated as Output, for presenting the fraud warnings and other disclosures required by Applicable Laws, and for obtaining the applicant's signature and attestation. Output is a draft and is not an attestation by CoverForce or by any person.",
        "(d) Disclosure; consumer rights. Customer is responsible for disclosing its use of artificial intelligence to applicants and insureds where Applicable Laws or a carrier require it, and for responding to any notice, explanation, appeal or opt-out request arising under Applicable Laws or a carrier's requirements.",
        "(e) Restrictions. Customer shall not, and shall not permit any Authorized User to: (i) use the AI Features or any Output to develop, train, fine-tune or improve any artificial intelligence or machine learning model; (ii) represent any Output as approved, verified or endorsed by CoverForce or by any carrier; (iii) represent any Output as a wholly human-generated work where Applicable Laws require otherwise; (iv) use the AI Features to make or automate any decision producing legal or similarly significant effects on an individual without the human review required by paragraph (b); (v) use the AI Features to infer, predict or make decisions on the basis of race, color, religion, national origin, sex, sexual orientation, gender identity, age, disability or any other characteristic protected by Applicable Laws, except as expressly permitted by Applicable Laws; (vi) submit to the AI Features any data that Customer lacks the right to submit; or (vii) use the AI Features in connection with any personal lines or life business transacted through the Services, or in connection with any risk located outside the United States, without CoverForce's prior written consent.",
        "(f) Model providers. CoverForce uses third-party model providers to deliver certain AI Features and may change them from time to time. CoverForce's rights in De-identified Data under Section 10 are unaffected by this paragraph. Customer's use of Carrier Data with the AI Features remains subject to Section 8(c).",
        "(g) Changes to AI Features. CoverForce may modify, condition, suspend or discontinue any AI Feature or CoverForce Connector at any time, including to comply with Applicable Laws, regulatory direction or a carrier requirement, and will use commercially reasonable efforts to give notice of any material change. No refund or reduction in Fees is due on account of a change to the AI Features or any CoverForce Connector.",
        '(h) Connectors; third-party AI platforms. Where Customer uses a CoverForce Connector to access the Services through a third-party artificial intelligence assistant or platform under Customer\'s own account with that provider (a "Customer AI Account"): (i) Customer is solely responsible for the Customer AI Account, for the provider\'s terms, and for the provider\'s data retention, training and sharing settings; (ii) all Inputs submitted through the Connector are submitted at Customer\'s direction, and Customer represents that it has the right to submit them and has provided any notices to and obtained any consents from applicants and insureds that Applicable Laws require; (iii) Customer remains bound by Sections 8, 9(b), 9(c) and 11 as to everything submitted through the Connector; and (iv) CoverForce does not control, and disclaims all responsibility for, the third-party assistant or platform and anything it generates. Except as CoverForce enables under paragraph (j), no quote, rate, premium, appetite or eligibility response, declination, or other Carrier Data identifying a carrier or its decision is transmitted through a CoverForce Connector; a Connector returns only confirmation that the Services have received or processed a request, an aggregate count of the carriers or markets that have responded, and a link to the Services.',
        '(i) Early Access Features. CoverForce may make features, including CoverForce Connectors, available on a beta, preview or early-access basis ("Early Access Features"). Early Access Features are provided "as is," may be modified, limited or withdrawn at any time without notice, may be subject to separate usage limits, and are excluded from any support or availability commitment. Feedback on Early Access Features is governed by Section 5.',
        "(j) Carrier Data through Connectors. CoverForce may, for particular carriers and in its sole discretion, enable a CoverForce Connector to return Carrier Data to a Customer AI Account, and may withdraw that enablement for any carrier at any time without notice, liability or refund. Where enabled: (i) Carrier Data is transmitted to the Customer AI Account at Customer's direction; (ii) Section 8(c) applies to that Carrier Data in the Customer AI Account, and Customer shall configure the Customer AI Account so that Carrier Data is not retained beyond the session in which it is received and is not used to train, tune or improve any model; and (iii) CoverForce may condition enablement on additional requirements notified under Section 8(f). Enablement is effected through the Services and is not an amendment of this Agreement.",
      ],
    },
    {
      title: "10. Customer Data",
      paragraphs: [
        'For purposes of this Agreement, "Customer Data" shall mean any data, information or other material provided, uploaded, or submitted by Customer or its Authorized Users to the Service in the course of using the Service, including through a CoverForce Connector. Customer shall retain all right, title and interest in and to the Customer Data, including all intellectual property rights therein. Customer, not CoverForce, shall have sole responsibility for the accuracy, quality, integrity, legality, reliability, appropriateness, and intellectual property ownership or right to use of all Customer Data. CoverForce is not responsible to Customer for unauthorized access to Customer Data or the unauthorized use of the Service unless such access results from CoverForce\'s breach of Section 11. Customer is responsible for the use of the Service by any person to whom Customer has given access to the Service, even if Customer did not authorize such use. Customer agrees and acknowledges that Customer Data may be irretrievably deleted if Customer\'s account is ninety (90) days or more delinquent.',
        'Customer grants CoverForce a perpetual, irrevocable, worldwide, royalty-free, sublicensable and transferable licence to host, copy, store, process, transmit, display, modify, analyse, combine with other data, create derivative works from, commercialise and otherwise exploit Customer Data for any lawful business purpose, including to provide the Services, to comply with Applicable Laws and its carrier agreements, to develop, train and improve products, models, analytics and services, and to create and make available data products. This licence survives termination. CoverForce will not disclose Customer Data that identifies Customer\'s applicants or insureds to any third party for that third party\'s own solicitation or marketing of those applicants or insureds, and will not use Customer Data to solicit Customer\'s applicants or insureds for CoverForce\'s own account. The preceding sentence does not restrict CoverForce\'s use of Customer Data to provide the Services or to comply with Applicable Laws or its carrier agreements, its disclosure of Customer Data to carriers, its service providers or regulators as permitted by Section 11, or its use or disclosure of aggregated or De-identified Data. As between the parties, CoverForce owns all analytics, models, derived datasets, insights, benchmarks and other works it creates from Customer Data, and Customer has no right, title or interest in them. Deletion or return of Customer Data, whether on termination, at Customer\'s request or otherwise, does not affect any analytics, model, derived dataset or other work already created or CoverForce\'s rights in it. "De-identified Data" means Customer Data from which all Personal Information and all information identifying Customer or its Authorized Users has been removed. CoverForce may create, retain and use De-identified Data, and data relating to Customer\'s use of and the performance of the Services, on a perpetual, irrevocable, worldwide, royalty-free basis for any lawful business purpose, including improving, developing and training its products and services, and this right survives termination. CoverForce\'s use of Carrier Data is governed by its agreements with the applicable carriers. CoverForce may retain Customer Data, and records of Submissions and Authorized User activity, for as long as required by Applicable Laws, its carrier agreements or its record-retention policies, and may delete or return Customer Data where a carrier or Applicable Laws so require. Retained data remains subject to Section 11.',
      ],
    },
    {
      title: "11. Confidentiality; Personal Information",
      paragraphs: [
        '(a) Confidentiality. "Confidential Information" means non-public information disclosed by one party to the other under this Agreement that is marked confidential or would reasonably be understood to be confidential, and includes Carrier Data and the terms of this Agreement. It excludes information that is public through no fault of the recipient, already known to or independently developed by the recipient, or rightfully received from a third party without restriction. The recipient shall use Confidential Information only to perform or receive the Services, protect it with at least reasonable care, and disclose it only to personnel and advisers who need to know and are bound by equivalent obligations, or as required by law on prior notice where permitted. CoverForce may disclose Customer Data and Confidential Information to carriers, its subcontractors and, where required, regulators as necessary to provide the Services or comply with its carrier agreements. CoverForce\'s obligations under this paragraph apply only to Customer Data and Customer Credentials and are subject to Section 10; all other information Customer provides to CoverForce is Feedback under Section 5. These obligations survive five (5) years after termination, and indefinitely for Carrier Data and Personal Information.',
        '(b) Personal Information. "Personal Information" means nonpublic personal information under the Gramm-Leach-Bliley Act and personal information under applicable state privacy law. Customer represents that it collects and submits Personal Information lawfully and with any required notices and consents, and shall not submit Personal Information beyond what the applicable carrier application requires. CoverForce\'s collection, use and disclosure of Personal Information is described in the Privacy Policy.',
        "(c) Incidents. Customer shall notify CoverForce without undue delay, and in any event within twenty-four (24) hours of discovering or reasonably suspecting, any unauthorized access to Carrier Data or to the Services through Customer's account, Customer Credentials or a Customer AI Account, and shall reasonably cooperate on investigation. CoverForce will notify Customer of a security incident affecting Customer's Personal Information as and when required by Applicable Laws. Regulatory and consumer notifications remain the responsibility of the party that is the licensee or data owner under Applicable Laws.",
      ],
    },
    {
      title: "12. Term; Termination",
      paragraphs: [
        'This Agreement shall commence when Customer first accepts it and shall continue until the subscription is cancelled in accordance with this Section (the "Term"). The subscription runs and renews automatically for successive Billing Periods until cancelled.',
        "Cancellation by Customer. Customer may cancel at any time, and may do so only through the cancellation function in the Services. CoverForce does not accept cancellation by email, telephone, letter or any other channel, and a cancellation request made by any other means is not effective. Cancellation takes effect at the end of the Billing Period in which it is made, and Customer retains access to the Services until then. Fees already paid are not refunded and are not prorated. Overage Charges accrued through the effective date of cancellation remain payable. Cancellation during a Billing Period to which an Introductory Credit applies takes effect at the end of that Billing Period in the same way as any other cancellation.",
        "Cancellation by CoverForce. CoverForce may cancel Customer's subscription for any reason on thirty (30) days' notice, and immediately on notice if Customer breaches Section 2, 7, 8, 9 or 11 or if Fees remain unpaid following suspension.",
        "In the event of a material breach of this Agreement by either party, the non-breaching party may terminate this Agreement by providing written notice to the breaching party, provided that the breaching party does not materially cure such breach within thirty (30) days of receipt of such notice. Without limiting the foregoing, CoverForce may suspend or limit Customer's access to or use of the Service if (i) Customer's account is more than ten (10) days past due, or (ii) Customer's use of the Service results in (or is reasonably likely to result in) damage to or material degradation of the Service or any carrier system, or which interferes with CoverForce's ability to provide access to the Service to other customers. CoverForce may suspend the Services immediately on breach of Section 2, 8, 9 or 11.",
        "On the effective date of cancellation or termination, Customer's and its Authorized Users' right to use the Services ends. CoverForce may, at its discretion, make Customer Data available for export for up to thirty (30) days after that date. Customer Data may be irretrievably deleted ninety (90) days after the effective date. CoverForce's retention rights under Section 10 are unaffected.",
      ],
    },
    {
      title: "13. Indemnification",
      paragraphs: [
        'Customer shall defend, indemnify, and hold harmless CoverForce, its affiliates and each of its and its affiliates\' employees, contractors, directors, suppliers and representatives (collectively, the "Indemnitees") from all liabilities, claims, and expenses paid or payable to an unaffiliated third party (including reasonable attorneys\' fees) ("Losses"), that arise from or relate to any claim that (i) the Customer Data or Customer\'s use of the Service infringes, violates, or misappropriates any third party intellectual property or proprietary right, (ii) alleges Customer\'s noncompliance with Applicable Laws or breaches of Section 1, 2, 7, 8 (including 8(h)), 9 or 11, or (iii) is brought by a carrier, a network or aggregator, an applicant or insured, a third-party AI platform provider, or any other third party arising from the acts or omissions of Customer or its Authorized Users, including any breach of Section 8 or 11, any use or misuse of Customer Credentials or a Customer AI Account, any submission or bind request transmitted through the Services, and any reliance on Output. Customer\'s obligations under this Section are not subject to any limitation of liability in this Agreement.',
        "CoverForce will give Customer prompt notice of any claim for which it seeks indemnification (provided that a failure to do so relieves Customer of its obligations only to the extent Customer is materially prejudiced). CoverForce may control the defense and settlement of any claim at Customer's expense, and Customer shall not settle any claim without CoverForce's prior written consent.",
      ],
    },
    {
      title: "14. Disclaimer",
      paragraphs: [
        'EXCEPT AS EXPRESSLY SET FORTH HEREIN, THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" AND IS WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AND ANY WARRANTIES IMPLIED BY ANY COURSE OF PERFORMANCE, USAGE OF TRADE, OR COURSE OF DEALING, ALL OF WHICH ARE EXPRESSLY DISCLAIMED. WITHOUT LIMITING THE FOREGOING, COVERFORCE DOES NOT WARRANT THE ACCURACY, COMPLETENESS OR CURRENCY OF ANY OUTPUT, ANY CARRIER DATA, OR ANY APPLICATION OR SUBMISSION GENERATED THROUGH THE SERVICE, AND DOES NOT WARRANT THAT USE OF THE SERVICE WILL CAUSE CUSTOMER TO COMPLY WITH ANY APPLICABLE LAW. COVERFORCE HAS NO DUTY TO MONITOR CUSTOMER\'S USE OF THE SERVICES, TO VERIFY ANY APPLICATION OR SUBMISSION, OR TO ADVISE CUSTOMER ON COVERAGE, SUITABILITY OR COMPLIANCE, AND ASSUMES NO FIDUCIARY OR ADVISORY RELATIONSHIP WITH CUSTOMER.',
      ],
    },
    {
      title: "15. Insurance Role",
      paragraphs: [
        "CoverForce is a technology provider only. CoverForce is not an insurance carrier, producer, agent, broker, managing general agent or third-party administrator; it does not solicit, negotiate, sell or bind insurance, collect premium, adjust claims or service policies, and has no authority to do any of them on behalf of Customer or any carrier. Quotes and other Carrier Data are indications until confirmed by the carrier. Customer alone places and binds coverage, owes all duties to applicants and insureds, and is responsible for compliance with all insurance laws applicable to its activities through the Services. Nothing in the Services is coverage, suitability or legal advice.",
      ],
    },
    {
      title: "16. Limitation of Liability",
      paragraphs: [
        "EXCEPT FOR CUSTOMER'S INDEMNIFICATION OBLIGATIONS, IN NO EVENT SHALL EITHER PARTY, NOR ITS DIRECTORS, EMPLOYEES, AGENTS, PARTNERS, SUPPLIERS OR CONTENT PROVIDERS, BE LIABLE UNDER CONTRACT, TORT, STRICT LIABILITY, NEGLIGENCE OR ANY OTHER LEGAL OR EQUITABLE THEORY WITH RESPECT TO THE SUBJECT MATTER OF THIS AGREEMENT (I) FOR ANY LOST PROFITS, DATA LOSS, COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, OR SPECIAL, INDIRECT, INCIDENTAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES OF ANY KIND WHATSOEVER, SUBSTITUTE GOODS OR SERVICES (HOWEVER ARISING), (II) FOR ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE (REGARDLESS OF THE SOURCE OF ORIGINATION), (III) FOR ANY DIRECT DAMAGES IN EXCESS OF (IN THE AGGREGATE) THE FEES PAID (OR PAYABLE) BY CUSTOMER TO COVERFORCE HEREUNDER IN THE TWELVE (12) MONTHS PRIOR TO THE EVENT GIVING RISE TO A CLAIM HEREUNDER, OR (IV) IN THE CASE OF COVERFORCE, FOR ANY CARRIER DATA, OUTPUT, EARLY ACCESS FEATURE, OR THIRD-PARTY ASSISTANT OR PLATFORM ACCESSED THROUGH A COVERFORCE CONNECTOR. THE FOREGOING LIMITATIONS DO NOT APPLY TO (A) CUSTOMER'S INDEMNIFICATION OBLIGATIONS, OR (B) CUSTOMER'S BREACH OF SECTIONS 2, 7, 8, 9 OR 11.",
      ],
    },
    {
      title: "17. Dispute Resolution",
      paragraphs: [
        "(a) Informal resolution. Before commencing arbitration, the party raising a dispute shall give the other written notice describing it, and the parties shall attempt in good faith to resolve it for thirty (30) days.",
        "(b) Binding arbitration. Any dispute, claim or controversy arising out of or relating to this Agreement or the Services that is not resolved under paragraph (a) shall be finally resolved by binding arbitration administered by the American Arbitration Association under its Commercial Arbitration Rules then in effect, before a single arbitrator, seated in New York County, New York. This Section is governed by the Federal Arbitration Act. The arbitrator shall have exclusive authority to resolve any dispute relating to the interpretation, applicability or enforceability of this Agreement, including the arbitrability of any claim, except as provided in paragraph (c). Judgment on the award may be entered in any court of competent jurisdiction.",
        "(c) Class action waiver. THE PARTIES MAY BRING CLAIMS AGAINST EACH OTHER ONLY IN THEIR INDIVIDUAL CAPACITIES, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS, COLLECTIVE, CONSOLIDATED OR REPRESENTATIVE PROCEEDING. The arbitrator may not consolidate the claims of more than one party and may not preside over any form of class or representative proceeding. The enforceability of this paragraph shall be determined by a court and not by the arbitrator. If this paragraph is held unenforceable, paragraphs (b) and (c) shall be void in their entirety and the dispute shall be resolved in the courts identified in Section 18.",
        "(d) Exceptions. Either party may (i) bring an individual claim in a small claims court of competent jurisdiction, and (ii) seek injunctive or other equitable relief in a court of competent jurisdiction to protect its intellectual property or Confidential Information, in each case without first proceeding under paragraphs (a) and (b). Each party waives any right to trial by jury in any dispute not subject to arbitration.",
        "(e) Time to bring claims. Any claim by Customer arising out of or relating to this Agreement or the Services must be commenced within one (1) year after the cause of action accrues or is permanently barred.",
      ],
    },
    {
      title: "18. Miscellaneous",
      paragraphs: [
        "This Agreement represents the entire agreement between Customer and CoverForce with respect to the subject matter hereof, and supersedes all prior or contemporaneous communications and proposals (whether oral, written or electronic) between Customer and CoverForce with respect thereto. In the event of any conflict between this Agreement and the Privacy Policy, the website Terms of Service published at coverforce.com, or any other CoverForce policy or page, this Agreement controls as to Customer's use of the Services. The Agreement shall be governed by and construed in accordance with the laws of the State of New York, excluding its conflicts of law rules, and the parties consent to exclusive jurisdiction and venue in the state and federal courts located in New York County, New York, subject to Section 17.",
        "Notices to Customer may be given by email to the address associated with Customer's account or by posting within the Services, and are deemed given when sent or posted; Customer is responsible for keeping that address current. Notices to CoverForce must be sent to the address CoverForce publishes for legal notices and are deemed given when receipt is electronically confirmed. CoverForce's legal-notice address is legal@coverforce.com or such other address as CoverForce publishes in the Documentation. Cancellation must be effected through the Services as provided in Section 12 and may not be given by notice.",
        "Electronic communications. Customer consents to receive all notices, disclosures, invoices, amendments and other communications under this Agreement electronically, by email to the address on Customer's account or by posting within the Services, and agrees that electronic communications satisfy any legal requirement that they be in writing. Customer confirms it is able to access and retain electronic communications. Customer may withdraw this consent only by cancelling under Section 12.",
        "CoverForce may modify these Terms from time to time. CoverForce will post the modified Terms with a revised date and, for any change that materially and adversely affects Customer, will give notice by email to the administrative contact on Customer's account or through the Services at least thirty (30) days before the change takes effect. Customer's continued use of the Services on or after the effective date constitutes acceptance; if Customer does not agree, its sole remedy is to cancel under Section 12 before the change takes effect. Changes to the Fees are governed by Section 6(f). Except as set out in this paragraph, this Agreement may be amended only by a writing executed by both parties.",
        "Except for payment obligations, neither party shall be liable for any failure to perform its obligations hereunder where such failure results from any cause beyond such party's reasonable control, including, without limitation, the elements; fire; flood; severe weather; earthquake; vandalism; accidents; sabotage; power failure; denial of service attacks or similar attacks; Internet failure; failure or unavailability of a carrier, of a third-party AI assistant or platform or of a third-party model provider; acts of God and the public enemy; acts of war; acts of terrorism; riots; civil or public disturbances; strikes lock-outs or labor disruptions; any laws, orders, rules, regulations, acts or restraints of any government or governmental body or authority, civil or military, including the orders and judgments of courts.",
        "Neither party may assign any of its rights or obligations hereunder without the other party's consent; provided that (i) either party may assign all of its rights and obligations hereunder without such consent to a successor-in-interest in connection with a sale of substantially all of such party's business relating to this Agreement, and (ii) CoverForce may utilize subcontractors in the performance of its obligations hereunder. No agency, partnership, joint venture, or employment relationship is created as a result of this Agreement and neither party has any authority of any kind to bind the other in any respect. Nothing in this Agreement makes CoverForce an insurance producer, agent or broker, or an agent of Customer or of any carrier. In any action or proceeding to enforce rights under this Agreement, the prevailing party shall be entitled to recover costs and attorneys' fees. If any provision of this Agreement is held to be unenforceable for any reason, such provision shall be reformed only to the extent necessary to make it enforceable. The failure of either party to act with respect to a breach of this Agreement by the other party shall not constitute a waiver and shall not limit such party's rights with respect to such breach or any subsequent breaches. CoverForce is permitted to disclose that Customer is one of its customers to any third-party at its sole discretion. Customer grants CoverForce the right to use Customer's trademark and service marks for such purpose and for marketing purposes. Sections 5, 7, 8(c), 8(h), 9(c), 9(h), 11, 13, 14, 15, 16, 17 and 18, CoverForce's licence and rights under Section 10, and any accrued payment obligations, survive termination.",
      ],
    },
  ],
  footerNote: (
    <>
      Questions about this agreement can be sent to{" "}
      <a href="mailto:legal@coverforce.com" className={linkClass}>
        legal@coverforce.com
      </a>{" "}
      or through our{" "}
      <Link href="/contact" className={linkClass}>
        contact page
      </Link>
      .
    </>
  ),
};
